import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  // Initialize language from localStorage or default to 'en'
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    return savedLanguage && ['en', 'bm'].includes(savedLanguage) ? savedLanguage : 'en';
  });

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('preferred-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'bm' : 'en');
  };

  const setLanguageCode = (langCode) => {
    if (['en', 'bm'].includes(langCode)) {
      setLanguage(langCode);
    }
  };

  const translations = {
    en: {
      // Navigation translations
      mpDashboard: 'MP Dashboard',
      profile: 'Profile',
      login: 'Login',
      logout: 'Logout',
      issuePortal: 'Issue Portal',
      eduContent: 'Educational Content',
      forum: 'Forum',
      reports: 'Reports',
      feedback: 'Feedback',
      adminAccess: 'Admin Access',
      
      // User Dashboard translations
      followedMPs: 'Followed MPs',
      followedTopics: 'Followed Topics',
      bookmarkedEduContent: 'Bookmarked Education',
      bookmarkedIssues: 'Bookmarked Issues',
      bookmarkedDiscussions: 'Bookmarked Discussions',
      discussions: 'Discussions',
      replies: 'Replies',
      activities: 'Activities',
      bookmarks: 'Bookmarks',
      settings: 'Settings',
      language: 'Language',
      
      // Dashboard specific
      loadingDashboard: 'Loading dashboard...',
      errorLoadingDashboard: 'Error Loading Dashboard',
      unableToLoadDashboard: 'Unable to load your dashboard data.',
      tryAgain: 'Try Again',
      noUserData: 'No User Data',
      pleaseLoginToAccess: 'Please login to access your dashboard.',
      goToLogin: 'Go to Login',
      
      // Stats Grid
      activeFollowing: 'Active following',
      interestedTopics: 'Interested topics',
      educationalContent: 'Educational content',
      forumParticipation: 'Forum participation',
      
      // Quick Actions Section
      quickActions: 'Quick Actions',
      exploreMyParliament: 'Explore MyParliament',
      yourPinnedTabs: 'Your pinned tabs',
      pinTabsForQuickAccess: 'Pin tabs for quick access',
      discoverOurFeatures: 'Discover our features and content',
      noPinnedTabsYet: 'No pinned tabs yet',
      clickPinIconToAdd: 'Click the pin icon on any tab to add it to your Quick Actions',
      quickAccess: 'Quick Access',
      unpinFromQuickActions: 'Unpin from Quick Actions',
      navigation: 'Navigation',
      top10ActiveMPs: 'Top 10 most active MPs',
      completeDirectoryMPs: 'Complete directory of all MPs',
      yourCreatedDiscussionsLabel: 'Your created discussions',
      forumNotificationsLabel: 'Forum notifications',
      analyticsInsightsOverview: 'Analytics and insights overview',
      yourPersonalReports: 'Your personal reports',
      issuePortalSubmitTrack: 'Issue Portal - Submit and track issues',
      learnAboutGovernance: 'Learn about governance',
      reportsAnalyticsInsights: 'Reports - Analytics and insights',
      feedbackShareThoughts: 'Feedback - Share your thoughts',
      quickAccessToFeature: 'Quick access to this feature',
      
      // Quick Action Descriptions
      exploreMembersOfParliament: 'Explore Members of Parliament',
      learnAboutParliamentaryProcesses: 'Learn about parliamentary processes',
      joinPoliticalDiscussions: 'Join political discussions',
      
      // User Profile Section
      yourDiscussions: 'Your Discussions',
      yourReplies: 'Your Replies',
      personalActivities: 'Personal Activities',
      discussionCreated: 'Discussion Created',
      noMoreDiscussions: 'No more discussions...',
      noMoreReplies: 'No more replies...',
      noMoreActivities: 'No more activities...',
      view: 'View',
      following: 'Following',
      bookmarked: 'Bookmarked',
      
      // Feedback Page
      feedbackAndSurvey: 'Feedback & Survey',
      shareYourThoughts: 'Share your thoughts and help us improve the platform',
      back: 'Back',
      sendFeedback: 'Send Feedback',
      platformSurvey: 'Platform Survey',
      sendFeedbackToAdmin: 'Send Feedback to Admin',
      shareYourThoughtsReportIssues: 'Share your thoughts, report issues, or suggest improvements to help us enhance the platform.',
      helpUsImprove: 'Help us improve the platform by sharing your experience and suggestions.',
      feedbackType: 'Feedback Type',
      priority: 'Priority',
      category: 'Category',
      subject: 'Subject',
      message: 'Message',
      generalFeedback: 'General Feedback',
      bugReport: 'Bug Report',
      featureRequest: 'Feature Request',
      improvementSuggestion: 'Improvement Suggestion',
      complaint: 'Complaint',
      compliment: 'Compliment',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
      ui: 'UI/UX',
      performance: 'Performance',
      functionality: 'Functionality',
      content: 'Content',
      accessibility: 'Accessibility',
      mobile: 'Mobile',
      other: 'Other',
      subjectPlaceholder: 'Brief summary of your feedback',
      messagePlaceholder: 'Please provide detailed feedback...',
      submit: 'Submit',
      submitting: 'Submitting...',
      feedbackSubmitted: 'Feedback Submitted!',
      thankYouForFeedback: 'Thank you for your feedback. We appreciate your input and will review it carefully.',
      close: 'Close',
      errorSubmittingFeedback: 'Error submitting feedback. Please try again.',
      thankYouForYourFeedback: 'Thank you for your feedback!',
      failedToSubmitFeedback: 'Failed to submit feedback. Please try again.',
      briefDescriptionOfFeedback: 'Brief summary of your feedback',
      pleaseProvideDetailedFeedback: 'Please provide detailed feedback...',
      subjectRequired: 'Subject is required.',
      messageRequired: 'Message is required.',
      parliamentaryCategoryRequired: 'Category is required.',
      feedbackLinkedTopicRequired: 'Related parliamentary topic is required.',
      submitFeedback: 'Submit Feedback',
      providingFeedbackFor: 'Providing feedback for:',
      categoryColon: 'Category:',
      parliamentaryIssues: 'Parliamentary Issues',
      userInterface: 'User Interface',
      viewSentFeedback: 'View Sent Feedback',
      viewSentFeedbackDescription: 'Review the feedback you have submitted and any replies from admins.',
      noSentFeedbackYet: 'No sent feedback yet',
      noSentFeedbackDescription: 'Your submitted feedback will appear here.',
      noAdminReplyYet: 'No admin reply yet.',
      adminReply: 'Admin Reply',
      admin: 'Admin',
      loading: 'Loading...',
      notAvailable: 'Not available',
      pending: 'Pending',
      platformSurveyDescription: 'Help us improve by sharing your experience and suggestions.',
      howSatisfiedWithPlatform: 'How satisfied are you with the platform?',
      pleaseSelectSatisfaction: 'Please select your satisfaction level.',
      emailRequiredForFollowUp: 'Please enter your email for follow-up.',
      thankYouForCompletingSurvey: 'Thank you for completing the survey!',
      failedToSubmitSurvey: 'Failed to submit survey. Please try again.',
      whichAreasToImprove: 'Which areas would you like to see improved?',
      pleaseSelectAtLeastOneArea: 'Please select at least one area to improve.',
      userInterfaceDesign: 'User Interface Design',
      navigationUsability: 'Navigation & Usability',
      educationalContentQuality: 'Educational Content Quality',
      discussionForumFeatures: 'Discussion Forum Features',
      mpDashboardInformation: 'MP Dashboard Information',
      searchFunctionality: 'Search Functionality',
      mobileExperience: 'Mobile Experience',
      loadingSpeed: 'Loading Speed',
      contentOrganization: 'Content Organization',
      notificationSystem: 'Notification System',
      specificImprovementsSuggest: 'Specific improvements or suggestions',
      specificImprovementsRequired: 'Please provide your suggestions or improvements.',
      specificImprovementsPlaceholder: 'Share your ideas for improvements...',
      contactForFollowUp: 'I\'m happy to be contacted for follow-up',
      emailPlaceholder: 'e.g. your@email.com',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      feedbackOnTopicSubject: 'Feedback on: {topic}',
      feedbackOnTopicMessageIntro: 'I would like to provide feedback regarding the topic "{topic}".\n\n',

      // Settings Modal
      accountSettings: 'Account Settings',
      personalInformation: 'Personal Information',
      preferences: 'Preferences',
      security: 'Security',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      dateOfBirth: 'Date of Birth',
      profilePicture: 'Profile Picture',
      chooseFile: 'Choose File',
      noFileChosen: 'No file chosen',
      interfaceLanguage: 'Interface Language',
      english: 'English',
      malayBahasa: 'Malay (Bahasa Malaysia)',
      emailNotifications: 'Email Notifications',
      pushNotifications: 'Push Notifications',
      darkMode: 'Dark Mode',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      // Settings tabs
      notificationSettings: 'Notifications',
      profileSettings: 'Profile',
      passwordSettings: 'Password',
      helpSupport: 'Help & Support',
      // Notification preferences
      notificationPreferences: 'Notification Preferences',
      notificationChannels: 'How you receive notifications',
      notificationChannelsDesc: 'Choose whether to get updates by email or in-browser push.',
      notificationContent: 'What to be notified about',
      notificationContentDesc: 'Choose which types of updates you want to receive.',
      emailNotificationsDesc: 'Receive email updates about your account and platform activity',
      pushNotificationsDesc: 'Receive push notifications in your browser',
      mpActivities: 'MP Activities',
      mpActivitiesDesc: 'Updates when followed MPs have new activity',
      discussionUpdates: 'Discussion Updates',
      discussionUpdatesDesc: 'Replies and updates on your forum discussions',
      educationalContentDesc: 'New educational content and recommendations',
      moderationNotices: 'Forum moderation notices',
      moderationNoticesDesc: 'When your forum post or topic is moderated by an admin (e.g. restricted or hidden)',
      notificationFrequency: 'Notification Frequency',
      instant: 'Instant',
      dailyDigest: 'Daily Digest',
      weeklySummary: 'Weekly Summary',
      off: 'Off',
      savePreferences: 'Save Preferences',
      saving: 'Saving...',
      changing: 'Changing...',
      // Complete Profile (Step 2 Sign Up)
      completeYourProfile: 'Complete Your Profile',
      step2Of2: 'Step 2 of 2',
      almostThere: "You're almost there! Just a few more details.",
      backToStep1: 'Back to Step 1',
      completeProfile: 'Complete Profile',
      step2Of2TellUsMore: 'Step 2 of 2: Tell us a bit more about yourself',
      step1AccountDetails: 'Step 1: Account Details',
      step2ProfileInformation: 'Step 2: Profile Information',
      enterYourFirstName: 'Enter your first name',
      enterYourLastName: 'Enter your last name',
      selectState: 'Select your state',
      completingProfile: 'Completing profile...',
      completeProfileAndContinue: 'Complete Profile & Continue',
      settingUpYourParliamentaryProfile: 'Setting up your parliamentary profile...',
      profileCompleted: 'Profile Completed!',
      welcomeToMyParliament: 'Welcome to My Parliament! Your profile is now complete.',
      continueToDashboard: 'Continue to Dashboard',
      // Profile form
      firstName: 'First Name',
      lastName: 'Last Name',
      birthDate: 'Birth Date',
      enterBirthDate: 'Select birth date',
      federalConstituency: 'Federal Constituency',
      updateProfile: 'Update Profile',
      firstNameRequired: 'First name is required',
      lastNameRequired: 'Last name is required',
      birthDateRequired: 'Birth date is required',
      stateRequired: 'State is required',
      constituencyRequired: 'Constituency is required',
      currentPasswordRequired: 'Current password is required',
      newPasswordRequired: 'New password is required',
      newPasswordTooShort: 'New password must be at least 8 characters',
      confirmPasswordRequired: 'Please confirm your new password',
      passwordsDoNotMatch: 'New password and confirmation do not match',
      newPasswordSameAsCurrent: 'New password cannot be the same as current password',
      newPasswordRequirementsNotMet: 'Password must meet all requirements (8+ chars, uppercase, lowercase, number, special character)',
      // Logout confirmation
      confirmLogout: 'Confirm Log Out',
      logoutConfirmationMessage: 'Are you sure you want to log out?',
      // Help & Support
      frequentlyAskedQuestions: 'Frequently Asked Questions',
      faqDescription: 'Find answers to common questions',
      viewFaq: 'View FAQ',
      contactSupport: 'Contact Support',
      contactSupportDescription: 'Get help from our support team',
      contactUs: 'Contact Us',
      userGuide: 'User Guide',
      userGuideDescription: 'Learn how to use the platform',
      readGuide: 'Read Guide',
      feedbackDescription: 'Share your feedback and suggestions',
      aboutMyParliament: 'About MY Parliament',
      version: 'Version',
      copyright: 'Copyright',
      
      // Header Navigation
      home: 'Home',
      mps: 'MPs',
      education: 'Education',
      
      // Platform Survey
      platformSurveyTitle: 'Platform Survey',
      surveyIntroduction: 'Help us improve MyParliament by sharing your experience and suggestions.',
      overallSatisfaction: 'Overall Satisfaction',
      howSatisfiedAreYou: 'How satisfied are you with MyParliament overall?',
      veryDissatisfied: 'Very Dissatisfied',
      dissatisfied: 'Dissatisfied',
      neutral: 'Neutral',
      satisfied: 'Satisfied',
      verySatisfied: 'Very Satisfied',
      mostUsefulFeature: 'Most Useful Feature',
      whichFeatureMostUseful: 'Which feature do you find most useful?',
      mpProfiles: 'MP Profiles',
      educationalResources: 'Educational Resources',
      discussionForum: 'Discussion Forum',
      issueReporting: 'Issue Reporting',
      platformReports: 'Platform Reports',
      improvementSuggestions: 'Improvement Suggestions',
      whatImprovements: 'What improvements would you like to see?',
      improvementSuggestionsPlaceholder: 'Share your ideas for making MyParliament better...',
      additionalComments: 'Additional Comments',
      anyAdditionalComments: 'Any additional comments or feedback?',
      additionalCommentsPlaceholder: 'Share any other thoughts or suggestions...',
      submitSurvey: 'Submit Survey',
      surveySubmitted: 'Survey Submitted!',
      thankYouForSurvey: 'Thank you for taking the time to complete our survey. Your feedback is valuable to us.',
      
      // Forum Page
      engageCommunityBlurb: 'Engage with the community and share your views on parliamentary and civic issues.',
      forumDiscussions: 'Forum Discussions',
      createdForum: 'Created Forum',
      notification: 'Notification',
      allDiscussions: 'All Discussions',
      myDiscussions: 'My Discussions',
      notifications: 'Notifications',
      joinConversation: 'Join the conversation and share your thoughts on important political topics',
      reportLabel: 'Report',
      reportedLabel: 'Reported',
      commentHiddenByAdmin: '*The comment has been hidden by admin',
      createDiscussion: 'Create Discussion',
      loginToCreateDiscussion: 'Login to Create Discussion',
      loginToViewCreatedForum: 'view your created discussions',
      loginToViewNotifications: 'view notifications',
      searchDiscussions: 'Search discussions...',
      allCategories: 'All Categories',
      general: 'General',
      policy: 'Policy',
      economy: 'Economy',
      healthcare: 'Healthcare',
      environment: 'Environment',
      allSortOptions: 'All',
      latest: 'Latest',
      popular: 'Popular',
      mostReplies: 'Most Replies',
      loadingDiscussions: 'Loading discussions...',
      noDiscussionsFound: 'No discussions found',
      noDiscussionsFoundDescription: 'No discussions found matching your criteria. Try adjusting your search or filters.',
      clearFilters: 'Clear Filters',
      startFirstDiscussion: 'Start the first discussion!',
      beFirstToStart: 'Be the first to start a meaningful conversation in the forum.',
      repliesCount: 'replies',
      views: 'views',
      viewed: 'Viewed',
      createNewDiscussion: 'Create New Discussion',
      discussionTitle: 'Discussion Title',
      titlePlaceholder: 'Enter a clear and engaging title for your discussion',
      selectCategory: 'Select Category',
      addTags: 'Add Tags (Optional)',
      tagsPlaceholder: 'Add relevant tags separated by commas',
      debate: 'Debate',
      announcement: 'Announcement',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Share your thoughts and start the discussion...',
      create: 'Create',
      createDiscussionBtn: 'Create Discussion',
      edit: 'Edit',
      delete: 'Delete',
      expand: 'Expand',
      collapse: 'Collapse',
      noData: 'No data',
      forumNoData: 'No data',
      noDiscussionsYet: 'No discussions yet',
      startDiscussionCta: 'Start a discussion to get the conversation going.',
      createYourFirstDiscussion: 'Create your first discussion',
      topicHasNoDiscussion: 'This topic has no discussion recently.',
      otherTopic: 'Other topic:',
      createDiscussionFor: 'Create Discussion for:',
      startDiscussionAboutTopic: 'Start a discussion about this parliamentary topic',
      titleLabel: 'Title',
      enterDiscussionTitle: 'Enter discussion title',
      categoryLabel: 'Category',
      linkedTopicLabel: 'Related Parliamentary Topic',
      linkedTopicPlaceholder: 'e.g. Rapid Transit, Minimum Wage...',
      selectCategoryFirst: 'select a category first',
      autoFilledFromIssuePortal: 'Auto-filled from issue portal — you can change it.',
      discussionTitleRequired: 'Title is required.',
      discussionCategoryRequired: 'Category is required.',
      discussionLinkedTopicRequired: 'Related parliamentary topic is required.',
      discussionDescriptionRequired: 'Description is required.',
      reportDiscussion: 'Report Discussion',
      reportModalBody: 'Tell us briefly why you find this discussion offensive. Your report will be reviewed by moderators.',
      closeReportDialog: 'Close report dialog',
      reasonForReporting: 'Reason for reporting',
      reportPlaceholder: 'Example: Contains hate speech, harassment, or inappropriate language that violates community guidelines.',
      reportErrorMinLength: 'Please provide at least 10 characters explaining why this discussion is offensive.',
      reportErrorSubmitFailed: 'Failed to submit report. Please try again later.',
      submitReport: 'Submit Report',
      thankYou: 'Thank you',
      reportSentToModerators: 'Your report has been sent to the moderators.',
      ok: 'OK',
      myCreatedDiscussions: 'My Created Discussions',
      noNotifications: 'No notifications',
      notificationsEmptyDesc: 'You have no notifications at the moment.',
      forumPostingRestricted: 'Forum posting is restricted for your account',
      loginActionCreateDiscussion: 'create a discussion',
      loginActionBookmarkDiscussion: 'bookmark this discussion',
      loginActionReplyDiscussion: 'reply to this discussion',
      loginActionReportDiscussion: 'report this discussion',
      viewFullPostAndReplies: 'View full post and replies',

      // Educational Content
      eduContentDescription: 'Discover comprehensive educational resources about Malaysian parliamentary processes, government structures, and civic engagement. Learn, explore, and deepen your understanding of democracy in Malaysia.',
      totalResources: 'Total Resources',
      totalViews: 'Total Views',
      totalBookmarks: 'Total Bookmarks',
      learningResources: 'Learning Resources',
      comprehensiveMaterials: 'Comprehensive materials to enhance your understanding of Malaysian governance',
      loadingEducationalResources: 'Loading educational resources...',
      errorLoadingResources: 'Error Loading Resources',
      noValidImageData: 'No valid image data',
      educationalResource: 'Educational Resource',
      recent: 'Recent',
      quiz: 'Quiz',
      files: 'files',
      file: 'file',
      noResourcesAvailable: 'No Resources Available',
      resourcesWillAppear: 'Educational resources will appear here once they are added to the system.',
      enhanceCivicKnowledge: 'Enhance Your Civic Knowledge',
      bookmarkResourcesDescription: 'Bookmark educational resources that interest you and build your understanding of Malaysian parliamentary processes and democratic governance.',
      exploreAllResources: 'Explore All Resources',

      // Educational Detail
      loadingEducationalResource: 'Loading educational resource...',
      errorLoadingResource: 'Error Loading Resource',
      resourceNotFound: 'Resource not found',
      backToResources: 'Back to Resources',
      relatedThemes: 'Related Themes',
      description: 'Description',
      contentAttachments: 'Content Attachments',
      download: 'Download',
      quizzes: 'Quizzes',
      question: 'Question',
      loginToSubmitQuiz: 'Login to Submit Quiz',
      submitQuiz: 'Submit Quiz',
      scoreLabel: 'Score:',
      passed: 'Passed!',
      failed: 'Failed',
      quizAttachments: 'Quiz Attachments',

      // MP Dashboard
      mpDashboardDescription: 'Explore comprehensive information about Malaysian Members of Parliament. Discover their profiles, track their activities, and stay informed about parliamentary representatives across all constituencies.',
      totalMPs: 'Total MPs',
      activeMPs: 'Active MPs',
      all: 'All',
      constituencies: 'Constituencies',
      politicalParties: 'Political Parties',
      searchMPsPlaceholder: 'Search MPs by name, party, or constituency...',
      search: 'Search',
      allMPs: 'All MPs',
      activeMPsFilter: 'Active MPs',
      inactiveMPs: 'Inactive MPs',
      allParties: 'All Parties',
      barisanNasional: 'Barisan Nasional',
      pakatanHarapan: 'Pakatan Harapan',
      perikatanNasional: 'Perikatan Nasional',
      warisan: 'Warisan',
      muda: 'MUDA',
      independent: 'Independent',
      filtersActive: 'Filters active:',
      status: 'Status:',
      party: 'Party:',
      searchFilter: 'Search:',
      clearAllFilters: 'Clear all filters',
      errorLoadingData: 'Error Loading Data',
      featuredMPs: 'Featured MPs',
      featuredMPsDescription: 'Ranked by attendance, response, sentiment and engagement — MPs with full performance data only.',
      performanceScore: 'Score',
      noFeaturedMPs: 'No MPs with full performance data yet. Run the precompute scripts first.',
      loadingFeaturedMPs: 'Loading featured MPs...',
      featuredMPsHidden: 'Featured MPs Hidden',
      featuredMPsHiddenDescription: 'Featured MPs are hidden when filters are active to show filtered results.',
      clearFiltersToSeeFeatured: 'Clear filters to see Featured MPs',
      featuredMPsOnFirstPage: 'Featured MPs on First Page',
      featuredMPsOnFirstPageDescription: 'Featured MPs are only shown on the first page without filters.',
      goToFirstPage: 'Go to first page',
      allMPsSection: 'All MPs',
      allMPsDescription: 'Complete directory of Members of Parliament with filtering and search capabilities',
      loadingMPs: 'Loading MPs...',
      unknownMP: 'Unknown MP',
      constituencyNotSpecified: 'Constituency not specified',
      state: 'State',
      stateNotSpecified: 'Not specified',
      active: 'Active',
      inactive: 'Inactive',
      unknown: 'Unknown',
      mpPhoto: 'MP Photo',
      noMPsFound: 'No MPs Found',
      noMPsFoundDescription: 'No MPs found matching your search criteria.',
      showing: 'Showing',
      to: 'to',
      of: 'of',
      MPs: 'MPs',
      resourcesCount: 'resources',
      first: 'First',
      previous: 'Previous',
      page: 'Page',
      next: 'Next',
      last: 'Last',

      // MP Detail Window
      mpDetails: 'MP Details',
      tabOverview: 'Overview',
      tabPerformance: 'Performance',
      followers: 'followers',
      addBookmark: 'Add bookmark',
      removeBookmark: 'Remove bookmark',
      noParty: 'No Party',
      noConstituency: 'No Constituency',
      mpShort: 'MP',
      term: 'Term',
      unknownStatus: 'Unknown Status',
      currentTerm: 'Current Term',
      pastTerm: 'Past Term',
      veteranMP: 'Veteran MP',
      veteranTermsServed: 'terms served',
      firstTimeMP: 'First-Time MP',
      biography: 'Biography',
      biographyDefault1: 'A dedicated Member of Parliament representing',
      biographyDefault2: 'has been actively involved in parliamentary proceedings and constituency service. With a focus on',
      biographyDefault3: 'principles, they continue to work towards better representation and service to their constituents.',
      parliamentaryHistory: 'Parliamentary History',
      current: 'Current',
      pastTermShort: 'Past Term',
      partyLabel: 'Party',
      constituencyLabel: 'Constituency',
      stateLabel: 'State',
      postedLabel: 'Posted',
      updatedLabel: 'Updated',
      firstTime: 'First Time',
      contactInformation: 'Contact Information',
      noContactData: 'No contact information available.',
      email: 'Email',
      phone: 'Phone',
      fax: 'Fax',
      seatNumber: 'Seat Number',
      address: 'Address',
      viewParliamentProfile: 'View Parliament Profile',
      performanceMetrics: 'Performance Metrics',
      parliamentAttendance: 'Parliament Attendance',
      parliamentTermLabel: 'Parliament Term {n}',
      responseRate: 'Response Rate',
      askRate: 'Ask Rate',
      escalationRate: 'Escalation Rate',
      interjectionRate: 'Interjection Rate',
      sentimentScore: 'Sentiment Score',
      recentParliamentaryActivity: 'Recent Parliamentary Activity',
      dataCurrentlyNotAvailable: 'Data is currently not available.',
      performanceDataNotAvailable: 'Performance data not available for this MP yet.',
      noRecentParliamentaryActivity: 'No recent parliamentary activity found for this MP.',
      viewInIssuePortal: 'View in Issue Portal',
      browseIssuePortal: 'Browse Issue Portal',

      // Issue Portal
      issuePortalDescription: 'Explore highlighted parliamentary issue themes. Stay informed about key topics, bookmark your interests, and engage with the latest developments in Malaysian politics.',
      activeTopics: 'Active Topics',
      activeIssues: 'Active Issues',
      sessionsCovered: 'Sessions covered',
      distinctMesyuarat: 'Distinct Mesyuarat',
      totalStatements: 'Total Statements',
      searchTopicsPlaceholder: 'Search topics (e.g., Minimum Wages, Healthcare, Education)...',
      featuredTopics: 'Featured Topics',
      featuredTopicsDescription: 'Explore the latest parliamentary discussions and policy developments',
      failedToLoadTopics: 'Failed to load topics. Please try again later.',
      retry: 'Retry',
      noTopicsFound: 'No topics found matching your criteria.',
      topicImage: 'Topic Image',
      viewsCount: 'views',
      bookmarksCount: 'bookmarks',
      allTopics: 'All Topics',
      allParlimen: 'All Parlimen',
      allPenggal: 'All Penggal',
      allMesyuarat: 'All Mesyuarat',
      noIssuesFound: 'No issues found matching your criteria',
      noIssuesAvailable: 'No issues available',
      clearIssueFiltersSuggestion: 'Try clearing your filters or selecting a different session',

      // Reports Module
      trackYourParliamentaryEngagement: 'Track your parliamentary engagement and activity across the platform.',
      explorePublicAnalytics: 'Explore public analytics and insights about parliamentary activity.',
      dataAvailable: 'Data available',
      noTopicsYet: 'No topics yet',
      overview: 'Overview',
      myReports: 'My Reports',
      loadingReports: 'Loading reports...',
      errorOccurred: 'An error occurred',
      errorLoadingReports: 'Error Loading Reports',
      loginRequired: 'Login Required',
      loginRequiredMessage: 'Please log in to view your reports.',
      loginRequiredForBookmark: 'This action requires you to be logged in. Would you like to log in or cancel?',
      loginRequiredPrefix: 'You need to be logged in to ',
      loginRequiredSuffix: '. Would you like to proceed to the login page?',
      loginButton: 'Login',
      reportsTitle: 'Reports',
      reportsDescription: 'Comprehensive analytics and insights about your parliamentary engagement and platform activity.',
      viewExportPersonalReports: 'View and export your personal parliamentary activity reports.',
      myBookmarks: 'My Bookmarks',
      myDiscussionsReport: 'My Discussions',
      myLearning: 'My Learning',
      myActivity: 'My Activity',
      topics: 'Topics',
      mpsReport: 'MPs',
      resources: 'Resources',
      viewDetails: 'View Details',
      lastUpdated: 'Last updated:',
      forumActive: 'Forum active',
      noQuizDataAvailable: 'No quiz data available',
      avgScoreLabel: 'Avg score',
      mostActiveDayLabel: 'Most active day',
      thisMonth: 'This Month',
      lastActivityLabel: 'Last Activity',
      noActivity: 'No activity',
      noActivityDataAvailable: 'No activity data available',
      topicCategoriesDistribution: 'Topic Categories Distribution',
      mostViewedTopics: 'Most Viewed Topics',
      mostViewedTopicsDescription: 'Based on Issue Portal views across active topics',
      topTopicsByViews: 'Top topics by views',
      noViewDataYet: 'No view data yet',
      mostViewedTopicsEmptyHint: 'Once Issue Portal topics start receiving views, the most viewed topics will appear here.',
      exportLabel: 'Export',
      exportReport: 'Export Report',
      print: 'Print',
      exportChartComingSoon: 'Export chart (coming soon)',
      items: 'items',
      noEduBookmarks: 'No education bookmarks yet',
      loginToExport: 'Login to export',
      noTopicCategoriesData: 'No topic categories data available',
      startMLForTopicInsights: 'Start your machine learning process to generate topic insights',
      topPerformingMPs: 'Top Performing MPs',
      responses: 'responses',
      attendance: 'attendance',
      myActivitySummary: 'My Activity Summary',
      topicsBookmarked: 'Topics Bookmarked',
      issuesYouFollowing: 'Issues you\'re following',
      forumDiscussionsCreated: 'Forum Discussions',
      discussionsParticipatedIn: 'Discussions you\'ve participated in',
      educationalResourcesViewed: 'Educational Resources',
      resourcesAccessed: 'Resources you\'ve accessed',
      feedbackSubmittedCount: 'Feedback Submitted',
      feedbackYouProvided: 'Feedback you\'ve provided',
      topicsBookmarkedDesc: 'Parliamentary topics you\'ve saved for reference',
      noMPsFollowedYet: 'No MPs followed yet',
      noRecentActivity: 'No recent activity',
      startEngagingPlatform: 'Start engaging with the platform to see your activity here',
      reportMyActivitySummaryTitle: 'My Activity Summary',
      reportMyActivitySummaryDesc: 'Complete overview of your platform engagement, bookmarks, and interactions',
      reportMyLearningProgressTitle: 'My Learning Progress',
      reportMyLearningProgressDesc: 'Educational resources accessed, quiz scores, and learning achievements',
      reportMyMPInteractionsTitle: 'My MP Interactions',
      reportMyMPInteractionsDesc: 'MPs you follow, questions asked, responses received, and engagement history',
      reportMyDiscussionHistoryTitle: 'My Discussion History',
      reportMyDiscussionHistoryDesc: 'All your forum posts, replies, and community participation details',
      reportMyBookmarkCollectionTitle: 'My Bookmark Collection',
      reportMyBookmarkCollectionDesc: 'All your bookmarked topics and MPs with detailed information and notes',
      reportMyFeedbackSurveysTitle: 'My Feedback & Surveys',
      reportMyFeedbackSurveysDesc: 'All feedback submitted, surveys completed, and suggestions provided',
      never: 'Never',
      totalActivities: 'total activities',
      certificates: 'certificates',
      mpsFollowed: 'MPs followed',
      questions: 'questions',
      parties: 'parties',
      categories: 'categories',
      total: 'total',
      surveys: 'surveys',
      suggestions: 'suggestions',
      rating: 'rating',
      noRating: 'No rating',

      // Generic navigation
      backToPreviousPage: 'Back to previous page',

      // Topic Detail (Issue Portal detail)
      loadingTopicDetails: 'Loading topic details...',
      topicNotFoundTitle: 'Topic Not Found',
      topicNotFoundMessage: 'Unable to load topic details. The issue portal data may not be precomputed yet.',
      backToIssuePortal: 'Back to Issue Portal',
      latestUpdateLabel: 'Latest update:',
      viewTopicDiscussion: 'View topic discussion',
      feedbackOnTopic: 'Feedback on Topic',
      statementsLabel: 'Statements',
      mpsInvolved: 'MPs involved',
      sourceDocuments: 'Source documents',
      topicDescription: 'Topic description',
      mostRecentUpdate: 'Most recent update',
      parliamentaryTimeline: 'Parliamentary Timeline',
      jumpToDate: 'Jump to date:',
      qualityLabel: 'quality',
      clickHereToViewTimeline: 'Click here to view full statement and chronology in the timeline below.',
      turnsLabel: 'turns',
      sessionDatesLabel: 'session dates',
      noParliamentaryRecords: 'No parliamentary records for this topic yet.',
      runPrecomputeHint: 'Run the precompute script to populate this data.',
      conversationLabel: 'conversation',
      conversationsLabel: 'conversations',
      conversationN: 'Conversation',
      turnLabel: 'turn',
      sentimentLabel: 'Sentiment:',
      turnTypeEscalate: 'Escalate',
      turnTypeAsk: 'Ask',
      turnTypeInterjection: 'Interjection',
      turnTypeReply: 'Reply',
      topicDescDiscussionsOn: 'Parliamentary discussions on',
      topicDescUnder: 'under',
      topicDescUnderTheme: 'Parliamentary discussions under the theme of',
      topicDescRecorded: 'Parliamentary discussions recorded in this session.',
      topicDescThisTopicSpans: 'This topic spans',
      topicDescStatement: 'statement',
      topicDescStatements: 'statements',
      topicDescMP: 'MP',
      topicDescMPs: 'MPs',
      topicDescSourceDoc: 'source document',
      topicDescSourceDocs: 'source documents',
      topicDescRecentDebate: 'Recent debate content:',
      forumDiscussionsDesc: 'Active discussions you\'ve started',
      educationalResourcesDesc: 'Learning materials you\'ve accessed',
      feedbackSubmittedDesc: 'Platform feedback and suggestions provided',
      myMPInteractions: 'My MP Interactions',
      mpsYouFollow: 'MPs You Follow',
      questionsAsked: 'Questions Asked',
      responsesReceived: 'Responses Received',
      yourRecentActivity: 'Your Recent Activity',
      bookmarkedTopic: 'Bookmarked Topic',
      postedDiscussion: 'Posted Discussion',
      completedQuiz: 'Completed Quiz',
      answered: 'Answered',
      submittedFeedback: 'Submitted Feedback',
      score: 'Score',
    },
    bm: {
      // Navigation translations
      mpDashboard: 'Dashboard Ahli Parlimen',
      profile: 'Profil',
      login: 'Log Masuk',
      logout: 'Log Keluar',
      issuePortal: 'Portal Isu',
      eduContent: 'Kandungan Pendidikan',
      forum: 'Forum',
      reports: 'Laporan',
      feedback: 'Maklum Balas',
      adminAccess: 'Akses Admin',
      
      // User Dashboard translations
      followedMPs: 'Ahli Parlimen Diikuti',
      followedTopics: 'Topik Diikuti',
      bookmarkedEduContent: 'Kandungan Pendidikan Ditandakan',
      bookmarkedIssues: 'Isu Ditandakan',
      bookmarkedDiscussions: 'Perbincangan Ditandakan',
      discussions: 'Perbincangan',
      replies: 'Balasan',
      activities: 'Aktiviti',
      bookmarks: 'Penanda Halaman',
      settings: 'Tetapan',
      language: 'Bahasa',
      
      // Dashboard specific
      loadingDashboard: 'Memuatkan dashboard...',
      errorLoadingDashboard: 'Ralat Memuatkan Dashboard',
      unableToLoadDashboard: 'Tidak dapat memuatkan data dashboard anda.',
      tryAgain: 'Cuba Lagi',
      noUserData: 'Tiada Data Pengguna',
      pleaseLoginToAccess: 'Sila log masuk untuk mengakses dashboard anda.',
      goToLogin: 'Pergi ke Log Masuk',
      
      // Stats Grid
      activeFollowing: 'Mengikuti aktif',
      interestedTopics: 'Topik yang diminati',
      educationalContent: 'Kandungan pendidikan',
      forumParticipation: 'Penyertaan forum',
      
      // Quick Actions Section
      quickActions: 'Tindakan Pantas',
      exploreMyParliament: 'Terokai MyParliament',
      yourPinnedTabs: 'Tab yang disematkan anda',
      pinTabsForQuickAccess: 'Sematkan tab untuk akses pantas',
      discoverOurFeatures: 'Temui ciri-ciri dan kandungan kami',
      noPinnedTabsYet: 'Belum ada tab yang disematkan',
      clickPinIconToAdd: 'Klik ikon pin pada mana-mana tab untuk menambahkannya ke Tindakan Pantas anda',
      quickAccess: 'Akses Pantas',
      unpinFromQuickActions: 'Nyahsemat dari Tindakan Pantas',
      navigation: 'Navigasi',
      top10ActiveMPs: '10 Ahli Parlimen paling aktif',
      completeDirectoryMPs: 'Direktori lengkap semua Ahli Parlimen',
      yourCreatedDiscussionsLabel: 'Perbincangan yang anda cipta',
      forumNotificationsLabel: 'Notifikasi forum',
      analyticsInsightsOverview: 'Tinjauan analitik dan wawasan',
      yourPersonalReports: 'Laporan peribadi anda',
      issuePortalSubmitTrack: 'Portal Isu - Hantar dan jejak isu',
      learnAboutGovernance: 'Ketahui tentang tadbir urus',
      reportsAnalyticsInsights: 'Laporan - Analitik dan wawasan',
      feedbackShareThoughts: 'Maklum balas - Kongsi pendapat anda',
      quickAccessToFeature: 'Akses pantas ke ciri ini',
      
      // Quick Action Descriptions
      exploreMembersOfParliament: 'Terokai Ahli-ahli Parlimen',
      learnAboutParliamentaryProcesses: 'Pelajari tentang proses parlimen',
      joinPoliticalDiscussions: 'Sertai perbincangan politik',
      
      // User Profile Section
      yourDiscussions: 'Perbincangan Anda',
      yourReplies: 'Balasan Anda',
      personalActivities: 'Aktiviti Peribadi',
      discussionCreated: 'Perbincangan Dibuat',
      noMoreDiscussions: 'Tiada lagi perbincangan...',
      noMoreReplies: 'Tiada lagi balasan...',
      noMoreActivities: 'Tiada lagi aktiviti...',
      view: 'Lihat',
      following: 'Mengikuti',
      bookmarked: 'Ditandakan',
      
      // Feedback Page
      feedbackAndSurvey: 'Maklum Balas & Tinjauan',
      shareYourThoughts: 'Kongsi pendapat anda dan bantu kami memperbaiki platform',
      back: 'Kembali',
      sendFeedback: 'Hantar Maklum Balas',
      platformSurvey: 'Tinjauan Platform',
      sendFeedbackToAdmin: 'Hantar Maklum Balas kepada Admin',
      shareYourThoughtsReportIssues: 'Kongsi pendapat anda, laporkan masalah, atau cadangkan penambahbaikan untuk membantu kami meningkatkan platform.',
      helpUsImprove: 'Bantu kami memperbaiki platform dengan berkongsi pengalaman dan cadangan anda.',
      feedbackType: 'Jenis Maklum Balas',
      priority: 'Keutamaan',
      category: 'Kategori',
      subject: 'Subjek',
      message: 'Mesej',
      generalFeedback: 'Maklum Balas Am',
      bugReport: 'Laporan Bug',
      featureRequest: 'Permintaan Ciri',
      improvementSuggestion: 'Cadangan Penambahbaikan',
      complaint: 'Aduan',
      compliment: 'Pujian',
      low: 'Rendah',
      medium: 'Sederhana',
      high: 'Tinggi',
      urgent: 'Mendesak',
      ui: 'UI/UX',
      performance: 'Prestasi',
      functionality: 'Fungsi',
      content: 'Kandungan',
      accessibility: 'Kebolehcapaian',
      mobile: 'Mudah Alih',
      other: 'Lain-lain',
      subjectPlaceholder: 'Ringkasan ringkas maklum balas anda',
      messagePlaceholder: 'Sila berikan maklum balas terperinci...',
      submit: 'Hantar',
      submitting: 'Menghantar...',
      feedbackSubmitted: 'Maklum Balas Dihantar!',
      thankYouForFeedback: 'Terima kasih atas maklum balas anda. Kami menghargai input anda dan akan mengkaji dengan teliti.',
      close: 'Tutup',
      errorSubmittingFeedback: 'Ralat menghantar maklum balas. Sila cuba lagi.',
      thankYouForYourFeedback: 'Terima kasih atas maklum balas anda!',
      failedToSubmitFeedback: 'Gagal menghantar maklum balas. Sila cuba lagi.',
      briefDescriptionOfFeedback: 'Ringkasan ringkas maklum balas anda',
      pleaseProvideDetailedFeedback: 'Sila berikan maklum balas terperinci...',
      subjectRequired: 'Subjek diperlukan.',
      messageRequired: 'Mesej diperlukan.',
      parliamentaryCategoryRequired: 'Kategori diperlukan.',
      feedbackLinkedTopicRequired: 'Topik parlimen berkaitan diperlukan.',
      submitFeedback: 'Hantar Maklum Balas',
      providingFeedbackFor: 'Memberi maklum balas untuk:',
      categoryColon: 'Kategori:',
      parliamentaryIssues: 'Isu Parlimen',
      userInterface: 'Antara Muka Pengguna',
      viewSentFeedback: 'Lihat Maklum Balas Dihantar',
      viewSentFeedbackDescription: 'Semak maklum balas yang telah anda hantar dan sebarang balasan daripada admin.',
      noSentFeedbackYet: 'Belum ada maklum balas dihantar',
      noSentFeedbackDescription: 'Maklum balas yang anda hantar akan dipaparkan di sini.',
      noAdminReplyYet: 'Belum ada balasan daripada admin.',
      adminReply: 'Balasan Admin',
      admin: 'Admin',
      loading: 'Memuatkan...',
      notAvailable: 'Tiada',
      pending: 'Menunggu',
      platformSurveyDescription: 'Bantu kami memperbaiki dengan berkongsi pengalaman dan cadangan anda.',
      howSatisfiedWithPlatform: 'Sejauh mana anda berpuas hati dengan platform?',
      pleaseSelectSatisfaction: 'Sila pilih tahap kepuasan anda.',
      emailRequiredForFollowUp: 'Sila masukkan emel anda untuk susulan.',
      thankYouForCompletingSurvey: 'Terima kasih kerana melengkapkan tinjauan!',
      failedToSubmitSurvey: 'Gagal menghantar tinjauan. Sila cuba lagi.',
      whichAreasToImprove: 'Bidang mana yang anda ingin lihat penambahbaikan?',
      pleaseSelectAtLeastOneArea: 'Sila pilih sekurang-kurangnya satu bidang untuk penambahbaikan.',
      userInterfaceDesign: 'Reka Bentuk Antara Muka',
      navigationUsability: 'Navigasi & Kebolehgunaan',
      educationalContentQuality: 'Kualiti Kandungan Pendidikan',
      discussionForumFeatures: 'Ciri Forum Perbincangan',
      mpDashboardInformation: 'Maklumat Dashboard Ahli Parlimen',
      searchFunctionality: 'Fungsi Carian',
      mobileExperience: 'Pengalaman Mudah Alih',
      loadingSpeed: 'Kelajuan Memuatkan',
      contentOrganization: 'Organisasi Kandungan',
      notificationSystem: 'Sistem Notifikasi',
      specificImprovementsSuggest: 'Penambahbaikan atau cadangan khusus',
      specificImprovementsRequired: 'Sila berikan cadangan atau penambahbaikan anda.',
      specificImprovementsPlaceholder: 'Kongsi idea anda untuk penambahbaikan...',
      contactForFollowUp: 'Saya bersetuju dihubungi untuk susulan',
      emailPlaceholder: 'cth. emel@anda.com',
      error: 'Ralat',
      success: 'Berjaya',
      warning: 'Amaran',
      feedbackOnTopicSubject: 'Maklum balas tentang: {topic}',
      feedbackOnTopicMessageIntro: 'Saya ingin memberi maklum balas mengenai topik "{topic}".\n\n',

      // Settings Modal
      accountSettings: 'Tetapan Akaun',
      personalInformation: 'Maklumat Peribadi',
      preferences: 'Keutamaan',
      security: 'Keselamatan',
      fullName: 'Nama Penuh',
      emailAddress: 'Alamat Emel',
      phoneNumber: 'Nombor Telefon',
      dateOfBirth: 'Tarikh Lahir',
      profilePicture: 'Gambar Profil',
      chooseFile: 'Pilih Fail',
      noFileChosen: 'Tiada fail dipilih',
      interfaceLanguage: 'Bahasa Antara Muka',
      english: 'Bahasa Inggeris',
      malayBahasa: 'Bahasa Malaysia',
      emailNotifications: 'Notifikasi Emel',
      pushNotifications: 'Notifikasi Tolak',
      darkMode: 'Mod Gelap',
      changePassword: 'Tukar Kata Laluan',
      currentPassword: 'Kata Laluan Semasa',
      newPassword: 'Kata Laluan Baru',
      confirmNewPassword: 'Sahkan Kata Laluan Baru',
      saveChanges: 'Simpan Perubahan',
      cancel: 'Batal',
      // Settings tabs
      notificationSettings: 'Notifikasi',
      profileSettings: 'Profil',
      passwordSettings: 'Kata Laluan',
      helpSupport: 'Bantuan & Sokongan',
      // Notification preferences
      notificationPreferences: 'Keutamaan Notifikasi',
      notificationChannels: 'Cara anda menerima notifikasi',
      notificationChannelsDesc: 'Pilih sama ada menerima kemas kini melalui emel atau notifikasi push dalam pelayar.',
      notificationContent: 'Perkara yang ingin diberitahu',
      notificationContentDesc: 'Pilih jenis kemas kini yang anda mahu terima.',
      emailNotificationsDesc: 'Terima kemas kini emel tentang akaun dan aktiviti platform anda',
      pushNotificationsDesc: 'Terima notifikasi push dalam pelayar anda',
      mpActivities: 'Aktiviti Ahli Parlimen',
      mpActivitiesDesc: 'Kemas kini apabila Ahli Parlimen yang diikuti mempunyai aktiviti baharu',
      discussionUpdates: 'Kemas Kini Perbincangan',
      discussionUpdatesDesc: 'Balasan dan kemas kini mengenai perbincangan forum anda',
      educationalContentDesc: 'Kandungan pendidikan baharu dan cadangan',
      moderationNotices: 'Notis moderasi forum',
      moderationNoticesDesc: 'Apabila siaran atau topik forum anda dimoderasi oleh admin (contoh: disekat atau disembunyikan)',
      notificationFrequency: 'Kekerapan Notifikasi',
      instant: 'Serta-merta',
      dailyDigest: 'Ringkasan Harian',
      weeklySummary: 'Ringkasan Mingguan',
      off: 'Mati',
      savePreferences: 'Simpan Keutamaan',
      saving: 'Menyimpan...',
      changing: 'Menukar...',
      // Complete Profile (Step 2 Sign Up)
      completeYourProfile: 'Lengkapkan Profil Anda',
      step2Of2: 'Langkah 2 daripada 2',
      almostThere: 'Anda hampir selesai! Hanya beberapa maklumat lagi.',
      backToStep1: 'Kembali ke Langkah 1',
      completeProfile: 'Lengkapkan Profil',
      step2Of2TellUsMore: 'Langkah 2 daripada 2: Beritahu kami lebih lanjut tentang anda',
      step1AccountDetails: 'Langkah 1: Maklumat Akaun',
      step2ProfileInformation: 'Langkah 2: Maklumat Profil',
      enterYourFirstName: 'Masukkan nama pertama anda',
      enterYourLastName: 'Masukkan nama akhir anda',
      selectState: 'Pilih negeri anda',
      completingProfile: 'Melengkapkan profil...',
      completeProfileAndContinue: 'Lengkapkan Profil & Teruskan',
      settingUpYourParliamentaryProfile: 'Menyediakan profil parlimen anda...',
      profileCompleted: 'Profil Dilengkapkan!',
      welcomeToMyParliament: 'Selamat datang ke My Parliament! Profil anda kini lengkap.',
      continueToDashboard: 'Teruskan ke Papan Pemuka',
      // Profile form
      firstName: 'Nama Pertama',
      lastName: 'Nama Akhir',
      birthDate: 'Tarikh Lahir',
      enterBirthDate: 'Pilih tarikh lahir',
      federalConstituency: 'Parlimen Persekutuan',
      updateProfile: 'Kemas Kini Profil',
      firstNameRequired: 'Nama pertama diperlukan',
      lastNameRequired: 'Nama akhir diperlukan',
      birthDateRequired: 'Tarikh lahir diperlukan',
      stateRequired: 'Negeri diperlukan',
      constituencyRequired: 'Parlimen diperlukan',
      currentPasswordRequired: 'Kata laluan semasa diperlukan',
      newPasswordRequired: 'Kata laluan baru diperlukan',
      newPasswordTooShort: 'Kata laluan baru mesti sekurang-kurangnya 8 aksara',
      confirmPasswordRequired: 'Sila sahkan kata laluan baru anda',
      passwordsDoNotMatch: 'Kata laluan baru dan pengesahan tidak sepadan',
      newPasswordSameAsCurrent: 'Kata laluan baru tidak boleh sama dengan kata laluan semasa',
      newPasswordRequirementsNotMet: 'Kata laluan mesti memenuhi semua syarat (8+ aksara, huruf besar, huruf kecil, nombor, aksara khas)',
      // Logout confirmation
      confirmLogout: 'Sahkan Log Keluar',
      logoutConfirmationMessage: 'Adakah anda pasti mahu log keluar?',
      // Help & Support
      frequentlyAskedQuestions: 'Soalan Lazim',
      faqDescription: 'Cari jawapan untuk soalan biasa',
      viewFaq: 'Lihat FAQ',
      contactSupport: 'Hubungi Sokongan',
      contactSupportDescription: 'Dapatkan bantuan daripada pasukan sokongan kami',
      contactUs: 'Hubungi Kami',
      userGuide: 'Panduan Pengguna',
      userGuideDescription: 'Pelajari cara menggunakan platform',
      readGuide: 'Baca Panduan',
      feedbackDescription: 'Kongsi maklum balas dan cadangan anda',
      aboutMyParliament: 'Perihal MY Parliament',
      version: 'Versi',
      copyright: 'Hak Cipta',
      
      // Header Navigation
      home: 'Laman Utama',
      mps: 'Ahli Parlimen',
      education: 'Pendidikan',
      
      // Platform Survey
      platformSurveyTitle: 'Tinjauan Platform',
      surveyIntroduction: 'Bantu kami memperbaiki MyParliament dengan berkongsi pengalaman dan cadangan anda.',
      overallSatisfaction: 'Kepuasan Keseluruhan',
      howSatisfiedAreYou: 'Sejauh mana anda berpuas hati dengan MyParliament secara keseluruhan?',
      veryDissatisfied: 'Sangat Tidak Berpuas Hati',
      dissatisfied: 'Tidak Berpuas Hati',
      neutral: 'Neutral',
      satisfied: 'Berpuas Hati',
      verySatisfied: 'Sangat Berpuas Hati',
      mostUsefulFeature: 'Ciri Paling Berguna',
      whichFeatureMostUseful: 'Ciri manakah yang anda rasa paling berguna?',
      mpProfiles: 'Profil Ahli Parlimen',
      educationalResources: 'Sumber Pendidikan',
      discussionForum: 'Forum Perbincangan',
      issueReporting: 'Pelaporan Isu',
      platformReports: 'Laporan Platform',
      improvementSuggestions: 'Cadangan Penambahbaikan',
      whatImprovements: 'Penambahbaikan apa yang anda ingin lihat?',
      improvementSuggestionsPlaceholder: 'Kongsi idea anda untuk menjadikan MyParliament lebih baik...',
      additionalComments: 'Komen Tambahan',
      anyAdditionalComments: 'Adakah anda mempunyai komen atau maklum balas tambahan?',
      additionalCommentsPlaceholder: 'Kongsi sebarang pemikiran atau cadangan lain...',
      submitSurvey: 'Hantar Tinjauan',
      surveySubmitted: 'Tinjauan Dihantar!',
      thankYouForSurvey: 'Terima kasih kerana meluangkan masa untuk melengkapkan tinjauan kami. Maklum balas anda sangat berharga bagi kami.',
      
      // Forum Page
      engageCommunityBlurb: 'Libatkan diri dengan komuniti dan kongsi pandangan anda tentang isu parlimen dan sivik.',
      forumDiscussions: 'Perbincangan Forum',
      createdForum: 'Forum Dicipta',
      notification: 'Notifikasi',
      allDiscussions: 'Semua Perbincangan',
      myDiscussions: 'Perbincangan Saya',
      notifications: 'Notifikasi',
      joinConversation: 'Sertai perbualan dan kongsi pemikiran anda tentang topik politik penting',
      reportLabel: 'Lapor',
      reportedLabel: 'Dilaporkan',
      commentHiddenByAdmin: '*Komen telah disembunyikan oleh admin',
      createDiscussion: 'Cipta Perbincangan',
      loginToCreateDiscussion: 'Log Masuk untuk Cipta Perbincangan',
      loginToViewCreatedForum: 'lihat perbincangan yang anda cipta',
      loginToViewNotifications: 'lihat notifikasi',
      searchDiscussions: 'Cari perbincangan...',
      allCategories: 'Semua Kategori',
      general: 'Am',
      policy: 'Dasar',
      economy: 'Ekonomi',
      healthcare: 'Kesihatan',
      environment: 'Alam Sekitar',
      allSortOptions: 'Semua',
      latest: 'Terkini',
      popular: 'Popular',
      mostReplies: 'Paling Banyak Balasan',
      loadingDiscussions: 'Memuatkan perbincangan...',
      noDiscussionsFound: 'Tiada perbincangan ditemui',
      noDiscussionsFoundDescription: 'Tiada perbincangan ditemui yang sepadan dengan kriteria anda. Cuba laraskan carian atau penapis anda.',
      clearFilters: 'Kosongkan Penapis',
      startFirstDiscussion: 'Mulakan perbincangan pertama!',
      beFirstToStart: 'Jadilah yang pertama memulakan perbualan bermakna di forum.',
      repliesCount: 'balasan',
      views: 'tontonan',
      viewed: 'Dilihat',
      createNewDiscussion: 'Cipta Perbincangan Baru',
      discussionTitle: 'Tajuk Perbincangan',
      titlePlaceholder: 'Masukkan tajuk yang jelas dan menarik untuk perbincangan anda',
      selectCategory: 'Pilih Kategori',
      addTags: 'Tambah Tag (Pilihan)',
      tagsPlaceholder: 'Tambah tag yang berkaitan dipisahkan dengan koma',
      debate: 'Debat',
      announcement: 'Pengumuman',
      descriptionLabel: 'Deskripsi',
      descriptionPlaceholder: 'Kongsi pemikiran anda dan mulakan perbincangan...',
      create: 'Cipta',
      createDiscussionBtn: 'Cipta Perbincangan',
      edit: 'Sunting',
      delete: 'Padam',
      expand: 'Kembangkan',
      collapse: 'Runtuhkan',
      noData: 'Tiada data',
      forumNoData: 'Tiada data',
      noDiscussionsYet: 'Belum ada perbincangan',
      startDiscussionCta: 'Mulakan perbincangan untuk memulakan perbualan.',
      createYourFirstDiscussion: 'Cipta perbincangan pertama anda',
      topicHasNoDiscussion: 'Topik ini tiada perbincangan baru-baru ini.',
      otherTopic: 'Topik lain:',
      createDiscussionFor: 'Cipta Perbincangan untuk:',
      startDiscussionAboutTopic: 'Mulakan perbincangan tentang topik parlimen ini',
      titleLabel: 'Tajuk',
      enterDiscussionTitle: 'Masukkan tajuk perbincangan',
      categoryLabel: 'Kategori',
      linkedTopicLabel: 'Topik Parlimen Berkaitan',
      linkedTopicPlaceholder: 'cth. Transit Pantas, Gaji Minimum...',
      selectCategoryFirst: 'pilih kategori dahulu',
      autoFilledFromIssuePortal: 'Diisi automatik dari portal isu — anda boleh mengubahnya.',
      discussionTitleRequired: 'Tajuk diperlukan.',
      discussionCategoryRequired: 'Kategori diperlukan.',
      discussionLinkedTopicRequired: 'Topik parlimen berkaitan diperlukan.',
      discussionDescriptionRequired: 'Deskripsi diperlukan.',
      reportDiscussion: 'Lapor Perbincangan',
      reportModalBody: 'Beritahu kami secara ringkas mengapa anda rasa perbincangan ini menyinggung. Laporan anda akan disemak oleh moderator.',
      closeReportDialog: 'Tutup dialog laporan',
      reasonForReporting: 'Sebab melaporkan',
      reportPlaceholder: 'Contoh: Mengandungi ujaran kebencian, gangguan, atau bahasa tidak sesuai yang melanggar garis panduan komuniti.',
      reportErrorMinLength: 'Sila berikan sekurang-kurangnya 10 aksara yang menerangkan mengapa perbincangan ini menyinggung.',
      reportErrorSubmitFailed: 'Gagal menghantar laporan. Sila cuba lagi nanti.',
      submitReport: 'Hantar Laporan',
      thankYou: 'Terima kasih',
      reportSentToModerators: 'Laporan anda telah dihantar kepada moderator.',
      ok: 'OK',
      myCreatedDiscussions: 'Perbincangan Dicipta Saya',
      noNotifications: 'Tiada notifikasi',
      notificationsEmptyDesc: 'Anda tiada notifikasi buat masa ini.',
      forumPostingRestricted: 'Penulisan forum disekat untuk akaun anda',
      loginActionCreateDiscussion: 'cipta perbincangan',
      loginActionBookmarkDiscussion: 'tandakan perbincangan ini',
      loginActionReplyDiscussion: 'balas perbincangan ini',
      loginActionReportDiscussion: 'lapor perbincangan ini',
      viewFullPostAndReplies: 'Lihat siaran penuh dan balasan',

      // Educational Content
      eduContentDescription: 'Temui sumber pendidikan yang komprehensif tentang proses parlimen Malaysia, struktur kerajaan, dan penglibatan sivik. Belajar, terokai, dan mendalami pemahaman anda tentang demokrasi di Malaysia.',
      totalResources: 'Jumlah Sumber',
      totalViews: 'Jumlah Tontonan',
      totalBookmarks: 'Jumlah Penanda',
      learningResources: 'Sumber Pembelajaran',
      comprehensiveMaterials: 'Bahan komprehensif untuk meningkatkan pemahaman anda tentang tadbir urus Malaysia',
      loadingEducationalResources: 'Memuatkan sumber pendidikan...',
      errorLoadingResources: 'Ralat Memuatkan Sumber',
      noValidImageData: 'Tiada data imej yang sah',
      educationalResource: 'Sumber Pendidikan',
      recent: 'Terkini',
      quiz: 'Kuiz',
      files: 'fail',
      file: 'fail',
      noResourcesAvailable: 'Tiada Sumber Tersedia',
      resourcesWillAppear: 'Sumber pendidikan akan muncul di sini setelah ditambahkan ke sistem.',
      enhanceCivicKnowledge: 'Tingkatkan Pengetahuan Sivik Anda',
      bookmarkResourcesDescription: 'Tandakan sumber pendidikan yang menarik minat anda dan bina pemahaman anda tentang proses parlimen Malaysia dan tadbir urus demokratik.',
      exploreAllResources: 'Terokai Semua Sumber',

      // Educational Detail
      loadingEducationalResource: 'Memuatkan sumber pendidikan...',
      errorLoadingResource: 'Ralat Memuatkan Sumber',
      resourceNotFound: 'Sumber tidak ditemui',
      backToResources: 'Kembali ke Sumber',
      relatedThemes: 'Tema Berkaitan',
      description: 'Deskripsi',
      contentAttachments: 'Lampiran Kandungan',
      download: 'Muat Turun',
      quizzes: 'Kuiz',
      question: 'Soalan',
      loginToSubmitQuiz: 'Log masuk untuk hantar kuiz',
      submitQuiz: 'Hantar Kuiz',
      scoreLabel: 'Skor:',
      passed: 'Lulus!',
      failed: 'Gagal',
      quizAttachments: 'Lampiran Kuiz',

      // MP Dashboard
      mpDashboardDescription: 'Terokai maklumat komprehensif tentang Ahli Parlimen Malaysia. Temui profil mereka, ikuti aktiviti mereka, dan kekal maklum tentang wakil parlimen di semua kawasan pilihan raya.',
      totalMPs: 'Jumlah Ahli Parlimen',
      activeMPs: 'Ahli Parlimen Aktif',
      all: 'Semua',
      constituencies: 'Kawasan Pilihan Raya',
      politicalParties: 'Parti Politik',
      searchMPsPlaceholder: 'Cari Ahli Parlimen mengikut nama, parti, atau kawasan pilihan raya...',
      search: 'Cari',
      allMPs: 'Semua Ahli Parlimen',
      activeMPsFilter: 'Ahli Parlimen Aktif',
      inactiveMPs: 'Ahli Parlimen Tidak Aktif',
      allParties: 'Semua Parti',
      barisanNasional: 'Barisan Nasional',
      pakatanHarapan: 'Pakatan Harapan',
      perikatanNasional: 'Perikatan Nasional',
      warisan: 'Warisan',
      muda: 'MUDA',
      independent: 'Bebas',
      filtersActive: 'Penapis aktif:',
      status: 'Status:',
      party: 'Parti:',
      searchFilter: 'Carian:',
      clearAllFilters: 'Kosongkan semua penapis',
      errorLoadingData: 'Ralat Memuatkan Data',
      featuredMPs: 'Ahli Parlimen Terpilih',
      featuredMPsDescription: 'Disusun berdasarkan kehadiran, respons, sentimen dan penglibatan — hanya AP dengan data prestasi lengkap.',
      performanceScore: 'Skor',
      noFeaturedMPs: 'Tiada AP dengan data prestasi lengkap lagi. Jalankan skrip pra-kira dahulu.',
      loadingFeaturedMPs: 'Memuatkan ahli parlimen terpilih...',
      featuredMPsHidden: 'Ahli Parlimen Terpilih Disembunyikan',
      featuredMPsHiddenDescription: 'Ahli Parlimen terpilih disembunyikan apabila penapis aktif untuk menunjukkan hasil yang ditapis.',
      clearFiltersToSeeFeatured: 'Kosongkan penapis untuk melihat Ahli Parlimen Terpilih',
      featuredMPsOnFirstPage: 'Ahli Parlimen Terpilih di Halaman Pertama',
      featuredMPsOnFirstPageDescription: 'Ahli Parlimen terpilih hanya ditunjukkan di halaman pertama tanpa penapis.',
      goToFirstPage: 'Pergi ke halaman pertama',
      allMPsSection: 'Semua Ahli Parlimen',
      allMPsDescription: 'Direktori lengkap Ahli Parlimen dengan keupayaan penapisan dan carian',
      loadingMPs: 'Memuatkan Ahli Parlimen...',
      unknownMP: 'Ahli Parlimen Tidak Diketahui',
      constituencyNotSpecified: 'Kawasan pilihan raya tidak dinyatakan',
      state: 'Negeri',
      stateNotSpecified: 'Tidak dinyatakan',
      active: 'Aktif',
      inactive: 'Tidak Aktif',
      unknown: 'Tidak Diketahui',
      mpPhoto: 'Foto Ahli Parlimen',
      noMPsFound: 'Tiada Ahli Parlimen Ditemui',
      noMPsFoundDescription: 'Tiada Ahli Parlimen ditemui yang sepadan dengan kriteria carian anda.',
      showing: 'Menunjukkan',
      to: 'hingga',
      of: 'daripada',
      MPs: 'Ahli Parlimen',
      resourcesCount: 'sumber',
      first: 'Pertama',
      previous: 'Sebelumnya',
      page: 'Halaman',
      next: 'Seterusnya',
      last: 'Terakhir',

      // MP Detail Window
      mpDetails: 'Butiran Ahli Parlimen',
      tabOverview: 'Gambaran Keseluruhan',
      tabPerformance: 'Prestasi',
      followers: 'pengikut',
      addBookmark: 'Tambah penanda',
      removeBookmark: 'Buang penanda',
      noParty: 'Tiada Parti',
      noConstituency: 'Tiada Kawasan',
      mpShort: 'Ahli Parlimen',
      term: 'Penggal',
      unknownStatus: 'Status Tidak Diketahui',
      currentTerm: 'Penggal Semasa',
      pastTerm: 'Penggal Lalu',
      veteranMP: 'Ahli Parlimen Berpengalaman',
      veteranTermsServed: 'penggal berkhidmat',
      firstTimeMP: 'Ahli Parlimen Kali Pertama',
      biography: 'Biografi',
      biographyDefault1: 'Seorang Ahli Parlimen yang berdedikasi mewakili',
      biographyDefault2: 'telah aktif dalam prosiding parlimen dan perkhidmatan kawasan. Dengan memberi tumpuan kepada prinsip',
      biographyDefault3: 'mereka terus berusaha untuk perwakilan dan perkhidmatan yang lebih baik kepada pengundi.',
      parliamentaryHistory: 'Sejarah Parlimen',
      current: 'Semasa',
      pastTermShort: 'Penggal Lalu',
      partyLabel: 'Parti',
      constituencyLabel: 'Kawasan',
      stateLabel: 'Negeri',
      postedLabel: 'Diterbitkan',
      updatedLabel: 'Dikemas kini',
      firstTime: 'Kali Pertama',
      contactInformation: 'Maklumat Perhubungan',
      noContactData: 'Tiada maklumat perhubungan.',
      email: 'Emel',
      phone: 'Telefon',
      fax: 'Faks',
      seatNumber: 'Nombor Kerusi',
      address: 'Alamat',
      viewParliamentProfile: 'Lihat Profil Parlimen',
      performanceMetrics: 'Metrik Prestasi',
      parliamentAttendance: 'Kehadiran Parlimen',
      parliamentTermLabel: 'Penggal Parlimen {n}',
      responseRate: 'Kadar Respons',
      askRate: 'Kadar Soalan',
      escalationRate: 'Kadar Eskalasi',
      interjectionRate: 'Kadar Sisipan',
      sentimentScore: 'Skor Sentimen',
      recentParliamentaryActivity: 'Aktiviti Parlimen Terkini',
      dataCurrentlyNotAvailable: 'Data belum tersedia pada masa ini.',
      performanceDataNotAvailable: 'Data prestasi belum tersedia untuk Ahli Parlimen ini.',
      noRecentParliamentaryActivity: 'Tiada aktiviti parlimen terkini ditemui untuk Ahli Parlimen ini.',
      viewInIssuePortal: 'Lihat dalam Portal Isu',
      browseIssuePortal: 'Terokai Portal Isu',

      // Issue Portal
      issuePortalDescription: 'Terokai tema isu parlimen yang ditonjolkan. Kekal maklum tentang topik utama, tandakan minat anda, dan libatkan diri dengan perkembangan terkini dalam politik Malaysia.',
      activeTopics: 'Topik Aktif',
      activeIssues: 'Isu Aktif',
      sessionsCovered: 'Sesi diliputi',
      distinctMesyuarat: 'Mesyuarat Berbeza',
      totalStatements: 'Jumlah Kenyataan',
      searchTopicsPlaceholder: 'Cari topik (cth: Gaji Minimum, Kesihatan, Pendidikan)...',
      featuredTopics: 'Topik Terpilih',
      featuredTopicsDescription: 'Terokai perbincangan parlimen terkini dan perkembangan dasar',
      failedToLoadTopics: 'Gagal memuatkan topik. Sila cuba lagi nanti.',
      retry: 'Cuba Lagi',
      noTopicsFound: 'Tiada topik ditemui yang sepadan dengan kriteria anda.',
      topicImage: 'Imej Topik',
      viewsCount: 'tontonan',
      bookmarksCount: 'penanda',
      allTopics: 'Semua Topik',
      allParlimen: 'Semua Parlimen',
      allPenggal: 'Semua Penggal',
      allMesyuarat: 'Semua Mesyuarat',
      noIssuesFound: 'Tiada isu ditemui yang sepadan dengan kriteria anda',
      noIssuesAvailable: 'Tiada isu tersedia',
      clearIssueFiltersSuggestion: 'Cuba kosongkan penapis atau pilih mesyuarat lain',

      // Reports Module
      trackYourParliamentaryEngagement: 'Jejak penglibatan parlimen dan aktiviti anda di seluruh platform.',
      explorePublicAnalytics: 'Terokai analitik awam dan wawasan tentang aktiviti parlimen.',
      dataAvailable: 'Data tersedia',
      noTopicsYet: 'Tiada topik lagi',
      overview: 'Gambaran Keseluruhan',
      myReports: 'Laporan Saya',
      loadingReports: 'Memuatkan laporan...',
      errorOccurred: 'Ralat berlaku',
      errorLoadingReports: 'Ralat Memuatkan Laporan',
      loginRequired: 'Log Masuk Diperlukan',
      loginRequiredMessage: 'Sila log masuk untuk melihat laporan anda.',
      loginRequiredForBookmark: 'Tindakan ini memerlukan anda log masuk. Adakah anda mahu log masuk atau batal?',
      loginRequiredPrefix: 'Anda perlu log masuk untuk ',
      loginRequiredSuffix: '. Adakah anda ingin pergi ke halaman log masuk?',
      loginButton: 'Log Masuk',
      reportsTitle: 'Laporan',
      reportsDescription: 'Analitik komprehensif dan wawasan tentang penglibatan parlimen dan aktiviti platform anda.',
      viewExportPersonalReports: 'Lihat dan eksport laporan aktiviti parlimen peribadi anda.',
      myBookmarks: 'Penanda Saya',
      myDiscussionsReport: 'Perbincangan Saya',
      myLearning: 'Pembelajaran Saya',
      myActivity: 'Aktiviti Saya',
      topics: 'Topik',
      mpsReport: 'Ahli Parlimen',
      resources: 'Sumber',
      viewDetails: 'Lihat Butiran',
      lastUpdated: 'Terakhir dikemas kini:',
      forumActive: 'Forum aktif',
      noQuizDataAvailable: 'Tiada data kuiz',
      avgScoreLabel: 'Skor purata',
      mostActiveDayLabel: 'Hari paling aktif',
      thisMonth: 'Bulan Ini',
      lastActivityLabel: 'Aktiviti Terkini',
      noActivity: 'Tiada aktiviti',
      noActivityDataAvailable: 'Tiada data aktiviti',
      topicCategoriesDistribution: 'Taburan Kategori Topik',
      mostViewedTopics: 'Topik Paling Dilihat',
      mostViewedTopicsDescription: 'Berdasarkan paparan Portal Isu merentas topik aktif',
      topTopicsByViews: 'Topik mengikut paparan',
      noViewDataYet: 'Tiada data paparan lagi',
      mostViewedTopicsEmptyHint: 'Setelah topik Portal Isu mula menerima paparan, topik paling dilihat akan dipaparkan di sini.',
      exportLabel: 'Eksport',
      exportReport: 'Eksport Laporan',
      print: 'Cetak',
      exportChartComingSoon: 'Eksport carta (akan datang)',
      items: 'item',
      noEduBookmarks: 'Tiada kandungan pendidikan ditandakan lagi',
      loginToExport: 'Log masuk untuk eksport',
      noTopicCategoriesData: 'Tiada data kategori topik',
      startMLForTopicInsights: 'Jalankan proses pembelajaran mesin untuk menjana wawasan topik',
      topPerformingMPs: 'Ahli Parlimen Berprestasi Tinggi',
      responses: 'respons',
      attendance: 'kehadiran',
      myActivitySummary: 'Ringkasan Aktiviti Saya',
      topicsBookmarked: 'Topik Ditandakan',
      issuesYouFollowing: 'Isu yang anda ikuti',
      forumDiscussionsCreated: 'Perbincangan Forum',
      discussionsParticipatedIn: 'Perbincangan yang anda sertai',
      educationalResourcesViewed: 'Sumber Pendidikan',
      resourcesAccessed: 'Sumber yang anda akses',
      feedbackSubmittedCount: 'Maklum Balas Dihantar',
      feedbackYouProvided: 'Maklum balas yang anda berikan',
      topicsBookmarkedDesc: 'Topik parlimen yang telah anda simpan untuk rujukan',
      noMPsFollowedYet: 'Tiada ahli parlimen diikuti lagi',
      noRecentActivity: 'Tiada aktiviti terkini',
      startEngagingPlatform: 'Mula berinteraksi dengan platform untuk melihat aktiviti anda di sini',
      reportMyActivitySummaryTitle: 'Ringkasan Aktiviti Saya',
      reportMyActivitySummaryDesc: 'Gambaran lengkap penglibatan platform, penanda halaman, dan interaksi anda',
      reportMyLearningProgressTitle: 'Kemajuan Pembelajaran Saya',
      reportMyLearningProgressDesc: 'Sumber pendidikan diakses, skor kuiz, dan pencapaian pembelajaran',
      reportMyMPInteractionsTitle: 'Interaksi Ahli Parlimen Saya',
      reportMyMPInteractionsDesc: 'Ahli parlimen yang anda ikuti, soalan ditanya, respons diterima, dan sejarah penglibatan',
      reportMyDiscussionHistoryTitle: 'Sejarah Perbincangan Saya',
      reportMyDiscussionHistoryDesc: 'Semua catatan forum, balasan, dan butiran penyertaan komuniti anda',
      reportMyBookmarkCollectionTitle: 'Koleksi Penanda Halaman Saya',
      reportMyBookmarkCollectionDesc: 'Semua topik dan ahli parlimen yang anda tandakan dengan maklumat dan nota terperinci',
      reportMyFeedbackSurveysTitle: 'Maklum Balas & Tinjauan Saya',
      reportMyFeedbackSurveysDesc: 'Semua maklum balas dihantar, tinjauan disiapkan, dan cadangan yang diberikan',
      never: 'Tiada',
      totalActivities: 'jumlah aktiviti',
      certificates: 'sijil',
      mpsFollowed: 'Ahli Parlimen diikuti',
      questions: 'soalan',
      parties: 'parti',
      categories: 'kategori',
      total: 'jumlah',
      surveys: 'tinjauan',
      suggestions: 'cadangan',
      rating: 'penilaian',
      noRating: 'Tiada penilaian',

      // Generic navigation
      backToPreviousPage: 'Kembali',

      // Topic Detail (Issue Portal detail)
      loadingTopicDetails: 'Memuatkan butiran topik...',
      topicNotFoundTitle: 'Topik Tidak Ditemui',
      topicNotFoundMessage: 'Tidak dapat memuatkan butiran topik. Data portal isu mungkin belum dipra-kira.',
      backToIssuePortal: 'Kembali ke Portal Isu',
      latestUpdateLabel: 'Kemaskini terkini:',
      viewTopicDiscussion: 'Lihat perbincangan topik',
      feedbackOnTopic: 'Maklum balas tentang topik',
      statementsLabel: 'Kenyataan',
      mpsInvolved: 'Ahli Parlimen terlibat',
      sourceDocuments: 'Dokumen sumber',
      topicDescription: 'Huraian topik',
      mostRecentUpdate: 'Kemaskini terkini',
      parliamentaryTimeline: 'Garis Masa Parlimen',
      jumpToDate: 'Lompat ke tarikh:',
      qualityLabel: 'kualiti',
      clickHereToViewTimeline: 'Klik di sini untuk melihat kenyataan penuh dan kronologi dalam garis masa di bawah.',
      turnsLabel: 'pusingan',
      sessionDatesLabel: 'tarikh sesi',
      noParliamentaryRecords: 'Tiada rekod parlimen untuk topik ini lagi.',
      runPrecomputeHint: 'Jalankan skrip pra-kira untuk mengisi data ini.',
      conversationLabel: 'perbualan',
      conversationsLabel: 'perbualan',
      conversationN: 'Perbualan',
      turnLabel: 'pusingan',
      sentimentLabel: 'Sentimen:',
      turnTypeEscalate: 'Eskalasi',
      turnTypeAsk: 'Tanya',
      turnTypeInterjection: 'Selaan',
      turnTypeReply: 'Balasan',
      topicDescDiscussionsOn: 'Perbincangan parlimen mengenai',
      topicDescUnder: 'di bawah',
      topicDescUnderTheme: 'Perbincangan parlimen di bawah tema',
      topicDescRecorded: 'Perbincangan parlimen direkodkan dalam sesi ini.',
      topicDescThisTopicSpans: 'Topik ini merangkumi',
      topicDescStatement: 'kenyataan',
      topicDescStatements: 'kenyataan',
      topicDescMP: 'Ahli Parlimen',
      topicDescMPs: 'Ahli Parlimen',
      topicDescSourceDoc: 'dokumen sumber',
      topicDescSourceDocs: 'dokumen sumber',
      topicDescRecentDebate: 'Kandungan debat terkini:',
      forumDiscussionsDesc: 'Perbincangan aktif yang telah anda mulakan',
      educationalResourcesDesc: 'Bahan pembelajaran yang telah anda akses',
      feedbackSubmittedDesc: 'Maklum balas platform dan cadangan yang diberikan',
      myMPInteractions: 'Interaksi Ahli Parlimen Saya',
      mpsYouFollow: 'Ahli Parlimen Yang Anda Ikuti',
      questionsAsked: 'Soalan Ditanya',
      responsesReceived: 'Respons Diterima',
      yourRecentActivity: 'Aktiviti Terkini Anda',
      bookmarkedTopic: 'Topik Ditandakan',
      postedDiscussion: 'Perbincangan Disiarkan',
      completedQuiz: 'Kuiz Selesai',
      answered: 'Dijawab',
      submittedFeedback: 'Maklum Balas Dihantar',
      score: 'Skor',
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage: setLanguageCode,
    toggleLanguage,
    t, // Translation function
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;