import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  // Initialize language from localStorage or default to 'en'
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    return savedLanguage && ['en', 'bm'].includes(savedLanguage) ? savedLanguage : 'en';
  });

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('preferred-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'bm' : 'en');
  };

  const setLanguageCode = (langCode) => {
    if (['en', 'bm'].includes(langCode)) {
      setLanguage(langCode);
    }
  };

  const translations = {
    en: {
      // Navigation translations
      mpDashboard: 'MP Dashboard',
      profile: 'Profile',
      login: 'Login',
      logout: 'Logout',
      issuePortal: 'Issue Portal',
      eduContent: 'Educational Content',
      forum: 'Forum',
      reports: 'Reports',
      feedback: 'Feedback',
      adminAccess: 'Admin Access',
      
      // User Dashboard translations
      followedMPs: 'Followed MPs',
      followedTopics: 'Followed Topics',
      bookmarkedEduContent: 'Bookmarked Education',
      bookmarkedIssues: 'Bookmarked Issues',
      discussions: 'Discussions',
      replies: 'Replies',
      activities: 'Activities',
      bookmarks: 'Bookmarks',
      settings: 'Settings',
      language: 'Language',
      
      // Dashboard specific
      loadingDashboard: 'Loading dashboard...',
      errorLoadingDashboard: 'Error Loading Dashboard',
      unableToLoadDashboard: 'Unable to load your dashboard data.',
      tryAgain: 'Try Again',
      noUserData: 'No User Data',
      pleaseLoginToAccess: 'Please login to access your dashboard.',
      goToLogin: 'Go to Login',
      
      // Stats Grid
      activeFollowing: 'Active following',
      interestedTopics: 'Interested topics',
      educationalContent: 'Educational content',
      forumParticipation: 'Forum participation',
      
      // Quick Actions Section
      quickActions: 'Quick Actions',
      exploreMyParliament: 'Explore MyParliament',
      yourPinnedTabs: 'Your pinned tabs',
      pinTabsForQuickAccess: 'Pin tabs for quick access',
      discoverOurFeatures: 'Discover our features and content',
      noPinnedTabsYet: 'No pinned tabs yet',
      clickPinIconToAdd: 'Click the pin icon on any tab to add it to your Quick Actions',
      quickAccess: 'Quick Access',
      unpinFromQuickActions: 'Unpin from Quick Actions',
      
      // Quick Action Descriptions
      exploreMembersOfParliament: 'Explore Members of Parliament',
      learnAboutParliamentaryProcesses: 'Learn about parliamentary processes',
      joinPoliticalDiscussions: 'Join political discussions',
      
      // User Profile Section
      yourDiscussions: 'Your Discussions',
      yourReplies: 'Your Replies',
      personalActivities: 'Personal Activities',
      discussionCreated: 'Discussion Created',
      noMoreDiscussions: 'No more discussions...',
      noMoreReplies: 'No more replies...',
      noMoreActivities: 'No more activities...',
      view: 'View',
      following: 'Following',
      bookmarked: 'Bookmarked',
      
      // Feedback Page
      feedbackAndSurvey: 'Feedback & Survey',
      shareYourThoughts: 'Share your thoughts and help us improve the platform',
      back: 'Back',
      sendFeedback: 'Send Feedback',
      platformSurvey: 'Platform Survey',
      sendFeedbackToAdmin: 'Send Feedback to Admin',
      shareYourThoughtsReportIssues: 'Share your thoughts, report issues, or suggest improvements to help us enhance the platform.',
      helpUsImprove: 'Help us improve the platform by sharing your experience and suggestions.',
      feedbackType: 'Feedback Type',
      priority: 'Priority',
      category: 'Category',
      subject: 'Subject',
      message: 'Message',
      generalFeedback: 'General Feedback',
      bugReport: 'Bug Report',
      featureRequest: 'Feature Request',
      improvementSuggestion: 'Improvement Suggestion',
      complaint: 'Complaint',
      compliment: 'Compliment',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
      ui: 'UI/UX',
      performance: 'Performance',
      functionality: 'Functionality',
      content: 'Content',
      accessibility: 'Accessibility',
      mobile: 'Mobile',
      other: 'Other',
      subjectPlaceholder: 'Brief summary of your feedback',
      messagePlaceholder: 'Please provide detailed feedback...',
      submit: 'Submit',
      submitting: 'Submitting...',
      feedbackSubmitted: 'Feedback Submitted!',
      thankYouForFeedback: 'Thank you for your feedback. We appreciate your input and will review it carefully.',
      close: 'Close',
      errorSubmittingFeedback: 'Error submitting feedback. Please try again.',
      
      // Settings Modal
      accountSettings: 'Account Settings',
      personalInformation: 'Personal Information',
      preferences: 'Preferences',
      security: 'Security',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      dateOfBirth: 'Date of Birth',
      profilePicture: 'Profile Picture',
      chooseFile: 'Choose File',
      noFileChosen: 'No file chosen',
      interfaceLanguage: 'Interface Language',
      english: 'English',
      malayBahasa: 'Malay (Bahasa Malaysia)',
      emailNotifications: 'Email Notifications',
      pushNotifications: 'Push Notifications',
      darkMode: 'Dark Mode',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      
      // Header Navigation
      home: 'Home',
      mps: 'MPs',
      education: 'Education',
      
      // Platform Survey
      platformSurveyTitle: 'Platform Survey',
      surveyIntroduction: 'Help us improve MyParliament by sharing your experience and suggestions.',
      overallSatisfaction: 'Overall Satisfaction',
      howSatisfiedAreYou: 'How satisfied are you with MyParliament overall?',
      veryDissatisfied: 'Very Dissatisfied',
      dissatisfied: 'Dissatisfied',
      neutral: 'Neutral',
      satisfied: 'Satisfied',
      verySatisfied: 'Very Satisfied',
      mostUsefulFeature: 'Most Useful Feature',
      whichFeatureMostUseful: 'Which feature do you find most useful?',
      mpProfiles: 'MP Profiles',
      educationalResources: 'Educational Resources',
      discussionForum: 'Discussion Forum',
      issueReporting: 'Issue Reporting',
      platformReports: 'Platform Reports',
      improvementSuggestions: 'Improvement Suggestions',
      whatImprovements: 'What improvements would you like to see?',
      improvementSuggestionsPlaceholder: 'Share your ideas for making MyParliament better...',
      additionalComments: 'Additional Comments',
      anyAdditionalComments: 'Any additional comments or feedback?',
      additionalCommentsPlaceholder: 'Share any other thoughts or suggestions...',
      submitSurvey: 'Submit Survey',
      surveySubmitted: 'Survey Submitted!',
      thankYouForSurvey: 'Thank you for taking the time to complete our survey. Your feedback is valuable to us.',
      
      // Forum Page
      forumDiscussions: 'Forum Discussions',
      createdForum: 'Created Forum',
      notification: 'Notification',
      allDiscussions: 'All Discussions',
      myDiscussions: 'My Discussions',
      notifications: 'Notifications',
      joinConversation: 'Join the conversation and share your thoughts on important political topics',
      createDiscussion: 'Create Discussion',
      loginToCreateDiscussion: 'Login to Create Discussion',
      searchDiscussions: 'Search discussions...',
      allCategories: 'All Categories',
      general: 'General',
      policy: 'Policy',
      economy: 'Economy',
      healthcare: 'Healthcare',
      environment: 'Environment',
      allSortOptions: 'All',
      latest: 'Latest',
      popular: 'Popular',
      mostReplies: 'Most Replies',
      loadingDiscussions: 'Loading discussions...',
      noDiscussionsFound: 'No discussions found',
      noDiscussionsFoundDescription: 'No discussions found matching your criteria. Try adjusting your search or filters.',
      clearFilters: 'Clear Filters',
      startFirstDiscussion: 'Start the first discussion!',
      beFirstToStart: 'Be the first to start a meaningful conversation in the forum.',
      repliesCount: 'replies',
      views: 'views',
      createNewDiscussion: 'Create New Discussion',
      discussionTitle: 'Discussion Title',
      titlePlaceholder: 'Enter a clear and engaging title for your discussion',
      selectCategory: 'Select Category',
      addTags: 'Add Tags (Optional)',
      tagsPlaceholder: 'Add relevant tags separated by commas',
      debate: 'Debate',
      announcement: 'Announcement',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Share your thoughts and start the discussion...',
      create: 'Create',
      createDiscussionBtn: 'Create Discussion',
      edit: 'Edit',
      delete: 'Delete',

      // Educational Content
      eduContentDescription: 'Discover comprehensive educational resources about Malaysian parliamentary processes, government structures, and civic engagement. Learn, explore, and deepen your understanding of democracy in Malaysia.',
      totalResources: 'Total Resources',
      totalViews: 'Total Views',
      totalBookmarks: 'Total Bookmarks',
      learningResources: 'Learning Resources',
      comprehensiveMaterials: 'Comprehensive materials to enhance your understanding of Malaysian governance',
      loadingEducationalResources: 'Loading educational resources...',
      errorLoadingResources: 'Error Loading Resources',
      noValidImageData: 'No valid image data',
      educationalResource: 'Educational Resource',
      recent: 'Recent',
      quiz: 'Quiz',
      files: 'files',
      file: 'file',
      noResourcesAvailable: 'No Resources Available',
      resourcesWillAppear: 'Educational resources will appear here once they are added to the system.',
      enhanceCivicKnowledge: 'Enhance Your Civic Knowledge',
      bookmarkResourcesDescription: 'Bookmark educational resources that interest you and build your understanding of Malaysian parliamentary processes and democratic governance.',
      exploreAllResources: 'Explore All Resources',

      // Educational Detail
      loadingEducationalResource: 'Loading educational resource...',
      errorLoadingResource: 'Error Loading Resource',
      resourceNotFound: 'Resource not found',
      backToResources: 'Back to Resources',
      relatedThemes: 'Related Themes',
      description: 'Description',
      contentAttachments: 'Content Attachments',
      download: 'Download',
      quizzes: 'Quizzes',
      question: 'Question',
      loginToSubmitQuiz: 'Login to Submit Quiz',
      submitQuiz: 'Submit Quiz',
      scoreLabel: 'Score:',
      passed: 'Passed!',
      failed: 'Failed',
      quizAttachments: 'Quiz Attachments',

      // MP Dashboard
      mpDashboardDescription: 'Explore comprehensive information about Malaysian Members of Parliament. Discover their profiles, track their activities, and stay informed about parliamentary representatives across all constituencies.',
      totalMPs: 'Total MPs',
      activeMPs: 'Active MPs',
      all: 'All',
      constituencies: 'Constituencies',
      politicalParties: 'Political Parties',
      searchMPsPlaceholder: 'Search MPs by name, party, or constituency...',
      search: 'Search',
      allMPs: 'All MPs',
      activeMPsFilter: 'Active MPs',
      inactiveMPs: 'Inactive MPs',
      allParties: 'All Parties',
      barisanNasional: 'Barisan Nasional',
      pakatanHarapan: 'Pakatan Harapan',
      perikatanNasional: 'Perikatan Nasional',
      warisan: 'Warisan',
      muda: 'MUDA',
      independent: 'Independent',
      filtersActive: 'Filters active:',
      status: 'Status:',
      party: 'Party:',
      searchFilter: 'Search:',
      clearAllFilters: 'Clear all filters',
      errorLoadingData: 'Error Loading Data',
      featuredMPs: 'Featured MPs',
      featuredMPsDescription: 'Top 10 most active and prominent Members of Parliament',
      loadingFeaturedMPs: 'Loading featured MPs...',
      featuredMPsHidden: 'Featured MPs Hidden',
      featuredMPsHiddenDescription: 'Featured MPs are hidden when filters are active to show filtered results.',
      clearFiltersToSeeFeatured: 'Clear filters to see Featured MPs',
      featuredMPsOnFirstPage: 'Featured MPs on First Page',
      featuredMPsOnFirstPageDescription: 'Featured MPs are only shown on the first page without filters.',
      goToFirstPage: 'Go to first page',
      allMPsSection: 'All MPs',
      allMPsDescription: 'Complete directory of Members of Parliament with filtering and search capabilities',
      loadingMPs: 'Loading MPs...',
      unknownMP: 'Unknown MP',
      constituencyNotSpecified: 'Constituency not specified',
      state: 'State',
      active: 'Active',
      inactive: 'Inactive',
      unknown: 'Unknown',
      mpPhoto: 'MP Photo',
      noMPsFound: 'No MPs Found',
      noMPsFoundDescription: 'No MPs found matching your search criteria.',
      showing: 'Showing',
      to: 'to',
      of: 'of',
      MPs: 'MPs',
      first: 'First',
      previous: 'Previous',
      page: 'Page',
      next: 'Next',
      last: 'Last',

      // MP Detail Window
      mpDetails: 'MP Details',
      tabOverview: 'Overview',
      tabPerformance: 'Performance',
      followers: 'followers',
      addBookmark: 'Add bookmark',
      removeBookmark: 'Remove bookmark',
      noParty: 'No Party',
      noConstituency: 'No Constituency',
      mpShort: 'MP',
      term: 'Term',
      unknownStatus: 'Unknown Status',
      currentTerm: 'Current Term',
      pastTerm: 'Past Term',
      veteranMP: 'Veteran MP',
      veteranTermsServed: 'terms served',
      firstTimeMP: 'First-Time MP',
      biography: 'Biography',
      biographyDefault1: 'A dedicated Member of Parliament representing',
      biographyDefault2: 'has been actively involved in parliamentary proceedings and constituency service. With a focus on',
      biographyDefault3: 'principles, they continue to work towards better representation and service to their constituents.',
      parliamentaryHistory: 'Parliamentary History',
      current: 'Current',
      pastTermShort: 'Past Term',
      partyLabel: 'Party:',
      constituencyLabel: 'Constituency:',
      firstTime: 'First Time',
      contactInformation: 'Contact Information',
      email: 'Email',
      phone: 'Phone',
      fax: 'Fax',
      seatNumber: 'Seat Number',
      address: 'Address',
      viewParliamentProfile: 'View Parliament Profile',
      performanceMetrics: 'Performance Metrics',
      parliamentAttendance: 'Parliament Attendance',
      responseRate: 'Response Rate',
      escalationRate: 'Escalation Rate',
      recentParliamentaryActivity: 'Recent Parliamentary Activity',

      // Issue Portal
      issuePortalDescription: 'Explore highlighted parliamentary issue themes. Stay informed about key topics, bookmark your interests, and engage with the latest developments in Malaysian politics.',
      activeTopics: 'Active Topics',
      searchTopicsPlaceholder: 'Search topics (e.g., Minimum Wages, Healthcare, Education)...',
      featuredTopics: 'Featured Topics',
      featuredTopicsDescription: 'Explore the latest parliamentary discussions and policy developments',
      failedToLoadTopics: 'Failed to load topics. Please try again later.',
      retry: 'Retry',
      noTopicsFound: 'No topics found matching your criteria.',
      topicImage: 'Topic Image',
      viewsCount: 'views',
      bookmarksCount: 'bookmarks',

      // Reports Module
      overview: 'Overview',
      myReports: 'My Reports',
      loading: 'Loading...',
      errorOccurred: 'An error occurred',
      loginRequired: 'Login Required',
      loginRequiredMessage: 'Please log in to view your reports.',
      loginButton: 'Login',
      reportsTitle: 'Reports',
      reportsDescription: 'Comprehensive analytics and insights about your parliamentary engagement and platform activity.',
      myBookmarks: 'My Bookmarks',
      myDiscussionsReport: 'My Discussions',
      myLearning: 'My Learning',
      myActivity: 'My Activity',
      topics: 'Topics',
      mpsReport: 'MPs',
      resources: 'Resources',
      viewDetails: 'View Details',
      lastUpdated: 'Last updated:',
      topicCategoriesDistribution: 'Topic Categories Distribution',
      topPerformingMPs: 'Top Performing MPs',
      responses: 'responses',
      attendance: 'attendance',
      myActivitySummary: 'My Activity Summary',
      topicsBookmarked: 'Topics Bookmarked',
      forumDiscussionsCreated: 'Forum Discussions',
      educationalResourcesViewed: 'Educational Resources',
      feedbackSubmittedCount: 'Feedback Submitted',
      topicsBookmarkedDesc: 'Parliamentary topics you\'ve saved for reference',
      forumDiscussionsDesc: 'Active discussions you\'ve started',
      educationalResourcesDesc: 'Learning materials you\'ve accessed',
      feedbackSubmittedDesc: 'Platform feedback and suggestions provided',
      myMPInteractions: 'My MP Interactions',
      mpsYouFollow: 'MPs You Follow',
      questionsAsked: 'Questions Asked',
      responsesReceived: 'Responses Received',
      yourRecentActivity: 'Your Recent Activity',
      bookmarkedTopic: 'Bookmarked Topic',
      postedDiscussion: 'Posted Discussion',
      completedQuiz: 'Completed Quiz',
      submittedFeedback: 'Submitted Feedback',
      score: 'Score',
    },
    bm: {
      // Navigation translations
      mpDashboard: 'Dashboard Ahli Parlimen',
      profile: 'Profil',
      login: 'Log Masuk',
      logout: 'Log Keluar',
      issuePortal: 'Portal Isu',
      eduContent: 'Kandungan Pendidikan',
      forum: 'Forum',
      reports: 'Laporan',
      feedback: 'Maklum Balas',
      adminAccess: 'Akses Admin',
      
      // User Dashboard translations
      followedMPs: 'Ahli Parlimen Diikuti',
      followedTopics: 'Topik Diikuti',
      bookmarkedEduContent: 'Kandungan Pendidikan Ditandakan',
      bookmarkedIssues: 'Isu Ditandakan',
      discussions: 'Perbincangan',
      replies: 'Balasan',
      activities: 'Aktiviti',
      bookmarks: 'Penanda Halaman',
      settings: 'Tetapan',
      language: 'Bahasa',
      
      // Dashboard specific
      loadingDashboard: 'Memuatkan dashboard...',
      errorLoadingDashboard: 'Ralat Memuatkan Dashboard',
      unableToLoadDashboard: 'Tidak dapat memuatkan data dashboard anda.',
      tryAgain: 'Cuba Lagi',
      noUserData: 'Tiada Data Pengguna',
      pleaseLoginToAccess: 'Sila log masuk untuk mengakses dashboard anda.',
      goToLogin: 'Pergi ke Log Masuk',
      
      // Stats Grid
      activeFollowing: 'Mengikuti aktif',
      interestedTopics: 'Topik yang diminati',
      educationalContent: 'Kandungan pendidikan',
      forumParticipation: 'Penyertaan forum',
      
      // Quick Actions Section
      quickActions: 'Tindakan Pantas',
      exploreMyParliament: 'Terokai MyParliament',
      yourPinnedTabs: 'Tab yang disematkan anda',
      pinTabsForQuickAccess: 'Sematkan tab untuk akses pantas',
      discoverOurFeatures: 'Temui ciri-ciri dan kandungan kami',
      noPinnedTabsYet: 'Belum ada tab yang disematkan',
      clickPinIconToAdd: 'Klik ikon pin pada mana-mana tab untuk menambahkannya ke Tindakan Pantas anda',
      quickAccess: 'Akses Pantas',
      unpinFromQuickActions: 'Nyahsemat dari Tindakan Pantas',
      
      // Quick Action Descriptions
      exploreMembersOfParliament: 'Terokai Ahli-ahli Parlimen',
      learnAboutParliamentaryProcesses: 'Pelajari tentang proses parlimen',
      joinPoliticalDiscussions: 'Sertai perbincangan politik',
      
      // User Profile Section
      yourDiscussions: 'Perbincangan Anda',
      yourReplies: 'Balasan Anda',
      personalActivities: 'Aktiviti Peribadi',
      discussionCreated: 'Perbincangan Dibuat',
      noMoreDiscussions: 'Tiada lagi perbincangan...',
      noMoreReplies: 'Tiada lagi balasan...',
      noMoreActivities: 'Tiada lagi aktiviti...',
      view: 'Lihat',
      following: 'Mengikuti',
      bookmarked: 'Ditandakan',
      
      // Feedback Page
      feedbackAndSurvey: 'Maklum Balas & Tinjauan',
      shareYourThoughts: 'Kongsi pendapat anda dan bantu kami memperbaiki platform',
      back: 'Kembali',
      sendFeedback: 'Hantar Maklum Balas',
      platformSurvey: 'Tinjauan Platform',
      sendFeedbackToAdmin: 'Hantar Maklum Balas kepada Admin',
      shareYourThoughtsReportIssues: 'Kongsi pendapat anda, laporkan masalah, atau cadangkan penambahbaikan untuk membantu kami meningkatkan platform.',
      helpUsImprove: 'Bantu kami memperbaiki platform dengan berkongsi pengalaman dan cadangan anda.',
      feedbackType: 'Jenis Maklum Balas',
      priority: 'Keutamaan',
      category: 'Kategori',
      subject: 'Subjek',
      message: 'Mesej',
      generalFeedback: 'Maklum Balas Am',
      bugReport: 'Laporan Bug',
      featureRequest: 'Permintaan Ciri',
      improvementSuggestion: 'Cadangan Penambahbaikan',
      complaint: 'Aduan',
      compliment: 'Pujian',
      low: 'Rendah',
      medium: 'Sederhana',
      high: 'Tinggi',
      urgent: 'Mendesak',
      ui: 'UI/UX',
      performance: 'Prestasi',
      functionality: 'Fungsi',
      content: 'Kandungan',
      accessibility: 'Kebolehcapaian',
      mobile: 'Mudah Alih',
      other: 'Lain-lain',
      subjectPlaceholder: 'Ringkasan ringkas maklum balas anda',
      messagePlaceholder: 'Sila berikan maklum balas terperinci...',
      submit: 'Hantar',
      submitting: 'Menghantar...',
      feedbackSubmitted: 'Maklum Balas Dihantar!',
      thankYouForFeedback: 'Terima kasih atas maklum balas anda. Kami menghargai input anda dan akan mengkaji dengan teliti.',
      close: 'Tutup',
      errorSubmittingFeedback: 'Ralat menghantar maklum balas. Sila cuba lagi.',
      
      // Settings Modal
      accountSettings: 'Tetapan Akaun',
      personalInformation: 'Maklumat Peribadi',
      preferences: 'Keutamaan',
      security: 'Keselamatan',
      fullName: 'Nama Penuh',
      emailAddress: 'Alamat Emel',
      phoneNumber: 'Nombor Telefon',
      dateOfBirth: 'Tarikh Lahir',
      profilePicture: 'Gambar Profil',
      chooseFile: 'Pilih Fail',
      noFileChosen: 'Tiada fail dipilih',
      interfaceLanguage: 'Bahasa Antara Muka',
      english: 'Bahasa Inggeris',
      malayBahasa: 'Bahasa Malaysia',
      emailNotifications: 'Notifikasi Emel',
      pushNotifications: 'Notifikasi Tolak',
      darkMode: 'Mod Gelap',
      changePassword: 'Tukar Kata Laluan',
      currentPassword: 'Kata Laluan Semasa',
      newPassword: 'Kata Laluan Baru',
      confirmNewPassword: 'Sahkan Kata Laluan Baru',
      saveChanges: 'Simpan Perubahan',
      cancel: 'Batal',
      
      // Header Navigation
      home: 'Laman Utama',
      mps: 'Ahli Parlimen',
      education: 'Pendidikan',
      
      // Platform Survey
      platformSurveyTitle: 'Tinjauan Platform',
      surveyIntroduction: 'Bantu kami memperbaiki MyParliament dengan berkongsi pengalaman dan cadangan anda.',
      overallSatisfaction: 'Kepuasan Keseluruhan',
      howSatisfiedAreYou: 'Sejauh mana anda berpuas hati dengan MyParliament secara keseluruhan?',
      veryDissatisfied: 'Sangat Tidak Berpuas Hati',
      dissatisfied: 'Tidak Berpuas Hati',
      neutral: 'Neutral',
      satisfied: 'Berpuas Hati',
      verySatisfied: 'Sangat Berpuas Hati',
      mostUsefulFeature: 'Ciri Paling Berguna',
      whichFeatureMostUseful: 'Ciri manakah yang anda rasa paling berguna?',
      mpProfiles: 'Profil Ahli Parlimen',
      educationalResources: 'Sumber Pendidikan',
      discussionForum: 'Forum Perbincangan',
      issueReporting: 'Pelaporan Isu',
      platformReports: 'Laporan Platform',
      improvementSuggestions: 'Cadangan Penambahbaikan',
      whatImprovements: 'Penambahbaikan apa yang anda ingin lihat?',
      improvementSuggestionsPlaceholder: 'Kongsi idea anda untuk menjadikan MyParliament lebih baik...',
      additionalComments: 'Komen Tambahan',
      anyAdditionalComments: 'Adakah anda mempunyai komen atau maklum balas tambahan?',
      additionalCommentsPlaceholder: 'Kongsi sebarang pemikiran atau cadangan lain...',
      submitSurvey: 'Hantar Tinjauan',
      surveySubmitted: 'Tinjauan Dihantar!',
      thankYouForSurvey: 'Terima kasih kerana meluangkan masa untuk melengkapkan tinjauan kami. Maklum balas anda sangat berharga bagi kami.',
      
      // Forum Page
      forumDiscussions: 'Perbincangan Forum',
      createdForum: 'Forum Dicipta',
      notification: 'Notifikasi',
      allDiscussions: 'Semua Perbincangan',
      myDiscussions: 'Perbincangan Saya',
      notifications: 'Notifikasi',
      joinConversation: 'Sertai perbualan dan kongsi pemikiran anda tentang topik politik penting',
      createDiscussion: 'Cipta Perbincangan',
      loginToCreateDiscussion: 'Log Masuk untuk Cipta Perbincangan',
      searchDiscussions: 'Cari perbincangan...',
      allCategories: 'Semua Kategori',
      general: 'Am',
      policy: 'Dasar',
      economy: 'Ekonomi',
      healthcare: 'Kesihatan',
      environment: 'Alam Sekitar',
      allSortOptions: 'Semua',
      latest: 'Terkini',
      popular: 'Popular',
      mostReplies: 'Paling Banyak Balasan',
      loadingDiscussions: 'Memuatkan perbincangan...',
      noDiscussionsFound: 'Tiada perbincangan ditemui',
      noDiscussionsFoundDescription: 'Tiada perbincangan ditemui yang sepadan dengan kriteria anda. Cuba laraskan carian atau penapis anda.',
      clearFilters: 'Kosongkan Penapis',
      startFirstDiscussion: 'Mulakan perbincangan pertama!',
      beFirstToStart: 'Jadilah yang pertama memulakan perbualan bermakna di forum.',
      repliesCount: 'balasan',
      views: 'tontonan',
      createNewDiscussion: 'Cipta Perbincangan Baru',
      discussionTitle: 'Tajuk Perbincangan',
      titlePlaceholder: 'Masukkan tajuk yang jelas dan menarik untuk perbincangan anda',
      selectCategory: 'Pilih Kategori',
      addTags: 'Tambah Tag (Pilihan)',
      tagsPlaceholder: 'Tambah tag yang berkaitan dipisahkan dengan koma',
      debate: 'Debat',
      announcement: 'Pengumuman',
      descriptionLabel: 'Deskripsi',
      descriptionPlaceholder: 'Kongsi pemikiran anda dan mulakan perbincangan...',
      create: 'Cipta',
      createDiscussionBtn: 'Cipta Perbincangan',
      edit: 'Sunting',
      delete: 'Padam',

      // Educational Content
      eduContentDescription: 'Temui sumber pendidikan yang komprehensif tentang proses parlimen Malaysia, struktur kerajaan, dan penglibatan sivik. Belajar, terokai, dan mendalami pemahaman anda tentang demokrasi di Malaysia.',
      totalResources: 'Jumlah Sumber',
      totalViews: 'Jumlah Tontonan',
      totalBookmarks: 'Jumlah Penanda',
      learningResources: 'Sumber Pembelajaran',
      comprehensiveMaterials: 'Bahan komprehensif untuk meningkatkan pemahaman anda tentang tadbir urus Malaysia',
      loadingEducationalResources: 'Memuatkan sumber pendidikan...',
      errorLoadingResources: 'Ralat Memuatkan Sumber',
      noValidImageData: 'Tiada data imej yang sah',
      educationalResource: 'Sumber Pendidikan',
      recent: 'Terkini',
      quiz: 'Kuiz',
      files: 'fail',
      file: 'fail',
      noResourcesAvailable: 'Tiada Sumber Tersedia',
      resourcesWillAppear: 'Sumber pendidikan akan muncul di sini setelah ditambahkan ke sistem.',
      enhanceCivicKnowledge: 'Tingkatkan Pengetahuan Sivik Anda',
      bookmarkResourcesDescription: 'Tandakan sumber pendidikan yang menarik minat anda dan bina pemahaman anda tentang proses parlimen Malaysia dan tadbir urus demokratik.',
      exploreAllResources: 'Terokai Semua Sumber',

      // Educational Detail
      loadingEducationalResource: 'Memuatkan sumber pendidikan...',
      errorLoadingResource: 'Ralat Memuatkan Sumber',
      resourceNotFound: 'Sumber tidak ditemui',
      backToResources: 'Kembali ke Sumber',
      relatedThemes: 'Tema Berkaitan',
      description: 'Deskripsi',
      contentAttachments: 'Lampiran Kandungan',
      download: 'Muat Turun',
      quizzes: 'Kuiz',
      question: 'Soalan',
      loginToSubmitQuiz: 'Log masuk untuk hantar kuiz',
      submitQuiz: 'Hantar Kuiz',
      scoreLabel: 'Skor:',
      passed: 'Lulus!',
      failed: 'Gagal',
      quizAttachments: 'Lampiran Kuiz',

      // MP Dashboard
      mpDashboardDescription: 'Terokai maklumat komprehensif tentang Ahli Parlimen Malaysia. Temui profil mereka, ikuti aktiviti mereka, dan kekal maklum tentang wakil parlimen di semua kawasan pilihan raya.',
      totalMPs: 'Jumlah Ahli Parlimen',
      activeMPs: 'Ahli Parlimen Aktif',
      all: 'Semua',
      constituencies: 'Kawasan Pilihan Raya',
      politicalParties: 'Parti Politik',
      searchMPsPlaceholder: 'Cari Ahli Parlimen mengikut nama, parti, atau kawasan pilihan raya...',
      search: 'Cari',
      allMPs: 'Semua Ahli Parlimen',
      activeMPsFilter: 'Ahli Parlimen Aktif',
      inactiveMPs: 'Ahli Parlimen Tidak Aktif',
      allParties: 'Semua Parti',
      barisanNasional: 'Barisan Nasional',
      pakatanHarapan: 'Pakatan Harapan',
      perikatanNasional: 'Perikatan Nasional',
      warisan: 'Warisan',
      muda: 'MUDA',
      independent: 'Bebas',
      filtersActive: 'Penapis aktif:',
      status: 'Status:',
      party: 'Parti:',
      searchFilter: 'Carian:',
      clearAllFilters: 'Kosongkan semua penapis',
      errorLoadingData: 'Ralat Memuatkan Data',
      featuredMPs: 'Ahli Parlimen Terpilih',
      featuredMPsDescription: '10 Ahli Parlimen yang paling aktif dan terkenal',
      loadingFeaturedMPs: 'Memuatkan ahli parlimen terpilih...',
      featuredMPsHidden: 'Ahli Parlimen Terpilih Disembunyikan',
      featuredMPsHiddenDescription: 'Ahli Parlimen terpilih disembunyikan apabila penapis aktif untuk menunjukkan hasil yang ditapis.',
      clearFiltersToSeeFeatured: 'Kosongkan penapis untuk melihat Ahli Parlimen Terpilih',
      featuredMPsOnFirstPage: 'Ahli Parlimen Terpilih di Halaman Pertama',
      featuredMPsOnFirstPageDescription: 'Ahli Parlimen terpilih hanya ditunjukkan di halaman pertama tanpa penapis.',
      goToFirstPage: 'Pergi ke halaman pertama',
      allMPsSection: 'Semua Ahli Parlimen',
      allMPsDescription: 'Direktori lengkap Ahli Parlimen dengan keupayaan penapisan dan carian',
      loadingMPs: 'Memuatkan Ahli Parlimen...',
      unknownMP: 'Ahli Parlimen Tidak Diketahui',
      constituencyNotSpecified: 'Kawasan pilihan raya tidak dinyatakan',
      state: 'Negeri',
      active: 'Aktif',
      inactive: 'Tidak Aktif',
      unknown: 'Tidak Diketahui',
      mpPhoto: 'Foto Ahli Parlimen',
      noMPsFound: 'Tiada Ahli Parlimen Ditemui',
      noMPsFoundDescription: 'Tiada Ahli Parlimen ditemui yang sepadan dengan kriteria carian anda.',
      showing: 'Menunjukkan',
      to: 'hingga',
      of: 'daripada',
      MPs: 'Ahli Parlimen',
      first: 'Pertama',
      previous: 'Sebelumnya',
      page: 'Halaman',
      next: 'Seterusnya',
      last: 'Terakhir',

      // MP Detail Window
      mpDetails: 'Butiran Ahli Parlimen',
      tabOverview: 'Gambaran Keseluruhan',
      tabPerformance: 'Prestasi',
      followers: 'pengikut',
      addBookmark: 'Tambah penanda',
      removeBookmark: 'Buang penanda',
      noParty: 'Tiada Parti',
      noConstituency: 'Tiada Kawasan',
      mpShort: 'Ahli Parlimen',
      term: 'Penggal',
      unknownStatus: 'Status Tidak Diketahui',
      currentTerm: 'Penggal Semasa',
      pastTerm: 'Penggal Lalu',
      veteranMP: 'Ahli Parlimen Berpengalaman',
      veteranTermsServed: 'penggal berkhidmat',
      firstTimeMP: 'Ahli Parlimen Kali Pertama',
      biography: 'Biografi',
      biographyDefault1: 'Seorang Ahli Parlimen yang berdedikasi mewakili',
      biographyDefault2: 'telah aktif dalam prosiding parlimen dan perkhidmatan kawasan. Dengan memberi tumpuan kepada prinsip',
      biographyDefault3: 'mereka terus berusaha untuk perwakilan dan perkhidmatan yang lebih baik kepada pengundi.',
      parliamentaryHistory: 'Sejarah Parlimen',
      current: 'Semasa',
      pastTermShort: 'Penggal Lalu',
      partyLabel: 'Parti:',
      constituencyLabel: 'Kawasan:',
      firstTime: 'Kali Pertama',
      contactInformation: 'Maklumat Perhubungan',
      email: 'Emel',
      phone: 'Telefon',
      fax: 'Faks',
      seatNumber: 'Nombor Kerusi',
      address: 'Alamat',
      viewParliamentProfile: 'Lihat Profil Parlimen',
      performanceMetrics: 'Metrik Prestasi',
      parliamentAttendance: 'Kehadiran Parlimen',
      responseRate: 'Kadar Respons',
      escalationRate: 'Kadar Eskalasi',
      recentParliamentaryActivity: 'Aktiviti Parlimen Terkini',

      // Issue Portal
      issuePortalDescription: 'Terokai tema isu parlimen yang ditonjolkan. Kekal maklum tentang topik utama, tandakan minat anda, dan libatkan diri dengan perkembangan terkini dalam politik Malaysia.',
      activeTopics: 'Topik Aktif',
      searchTopicsPlaceholder: 'Cari topik (cth: Gaji Minimum, Kesihatan, Pendidikan)...',
      featuredTopics: 'Topik Terpilih',
      featuredTopicsDescription: 'Terokai perbincangan parlimen terkini dan perkembangan dasar',
      failedToLoadTopics: 'Gagal memuatkan topik. Sila cuba lagi nanti.',
      retry: 'Cuba Lagi',
      noTopicsFound: 'Tiada topik ditemui yang sepadan dengan kriteria anda.',
      topicImage: 'Imej Topik',
      viewsCount: 'tontonan',
      bookmarksCount: 'penanda',

      // Reports Module
      overview: 'Gambaran Keseluruhan',
      myReports: 'Laporan Saya',
      loading: 'Memuatkan...',
      errorOccurred: 'Ralat berlaku',
      loginRequired: 'Log Masuk Diperlukan',
      loginRequiredMessage: 'Sila log masuk untuk melihat laporan anda.',
      loginButton: 'Log Masuk',
      reportsTitle: 'Laporan',
      reportsDescription: 'Analitik komprehensif dan wawasan tentang penglibatan parlimen dan aktiviti platform anda.',
      myBookmarks: 'Penanda Saya',
      myDiscussionsReport: 'Perbincangan Saya',
      myLearning: 'Pembelajaran Saya',
      myActivity: 'Aktiviti Saya',
      topics: 'Topik',
      mpsReport: 'Ahli Parlimen',
      resources: 'Sumber',
      viewDetails: 'Lihat Butiran',
      lastUpdated: 'Terakhir dikemas kini:',
      topicCategoriesDistribution: 'Taburan Kategori Topik',
      topPerformingMPs: 'Ahli Parlimen Berprestasi Tinggi',
      responses: 'respons',
      attendance: 'kehadiran',
      myActivitySummary: 'Ringkasan Aktiviti Saya',
      topicsBookmarked: 'Topik Ditandakan',
      forumDiscussionsCreated: 'Perbincangan Forum',
      educationalResourcesViewed: 'Sumber Pendidikan',
      feedbackSubmittedCount: 'Maklum Balas Dihantar',
      topicsBookmarkedDesc: 'Topik parlimen yang telah anda simpan untuk rujukan',
      forumDiscussionsDesc: 'Perbincangan aktif yang telah anda mulakan',
      educationalResourcesDesc: 'Bahan pembelajaran yang telah anda akses',
      feedbackSubmittedDesc: 'Maklum balas platform dan cadangan yang diberikan',
      myMPInteractions: 'Interaksi Ahli Parlimen Saya',
      mpsYouFollow: 'Ahli Parlimen Yang Anda Ikuti',
      questionsAsked: 'Soalan Ditanya',
      responsesReceived: 'Respons Diterima',
      yourRecentActivity: 'Aktiviti Terkini Anda',
      bookmarkedTopic: 'Topik Ditandakan',
      postedDiscussion: 'Perbincangan Disiarkan',
      completedQuiz: 'Kuiz Selesai',
      submittedFeedback: 'Maklum Balas Dihantar',
      score: 'Skor',
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage: setLanguageCode,
    toggleLanguage,
    t, // Translation function
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;